# 注意事项：
# 1. 数据存储于`/usr/local/dataflux-func/`目录下，
#    部署前应当保证目录已经存在。
#    参考命令：
#       sudo mkdir -p /usr/local/dataflux-func/{data,data/extra-python-packages,mysql,redis}
#
# 2. 使用`docker stack`即进行部署。
#    参考命令（假设本配置文件名为"docker-stack.yaml"）：
#       sudo docker stack deploy dataflux-func -c docker-stack.yaml
#
# 3. 如不需要内置MySQL 组件，请删除MYSQL相关的内容块
# 4. 如不需要内置Redis 组件，请删除REDIS相关的内容块
# 5. 如使用默认方式安装，请删除WORKER MINI 相关的内容块
# 6. 如使用mini 方式安装，请删除WORKER DEFAULT 相关的内容块

version: '3.1'

services:
  # MYSQL START
  mysql:
    image: <MYSQL_IMAGE>
    labels:
      - mysql
    networks:
      - datafluxfunc
    volumes:
      - "<INSTALL_DIR>/mysql:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=<MYSQL_PASSWORD>"
      - "MYSQL_DATABASE=dataflux_func"
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=off --table-open-cache=400
  # MYSQL END

  # REDIS START
  redis:
    image: <REDIS_IMAGE>
    labels:
      - redis
    networks:
      - datafluxfunc
    volumes:
      - "<INSTALL_DIR>/redis:/data"
  # REDIS END

  # WORKER DEFAULT START
  worker-0:
    image: <DATAFLUX_FUNC_IMAGE>
    labels:
      - worker-0
    volumes:
      - "<INSTALL_DIR>/data:/data"
    networks:
      - datafluxfunc
      - default
    environment:
      DFF__WORKER_CONCURRENCY: '2'
    command: ./run-worker-by-queue.sh 0

  worker-1-6:
    image: <DATAFLUX_FUNC_IMAGE>
    labels:
      - worker-1-6
    volumes:
      - "<INSTALL_DIR>/data:/data"
    networks:
      - datafluxfunc
      - default
    command: ./run-worker-by-queue.sh 1 2 3 4 5 6

  worker-7:
    image: <DATAFLUX_FUNC_IMAGE>
    labels:
      - worker-7
    volumes:
      - "<INSTALL_DIR>/data:/data"
    networks:
      - datafluxfunc
      - default
    environment:
      DFF__WORKER_CONCURRENCY: '2'
    command: ./run-worker-by-queue.sh 7

  worker-8-9:
    image: <DATAFLUX_FUNC_IMAGE>
    labels:
      - worker-8-9
    volumes:
      - "<INSTALL_DIR>/data:/data"
    networks:
      - datafluxfunc
      - default
    command: ./run-worker-by-queue.sh 8 9
  # WORKER DEFAULT END

  # WORKER MINI START
  worker:
    image: <DATAFLUX_FUNC_IMAGE>
    labels:
      - worker
    volumes:
      - "<INSTALL_DIR>/data:/data"
    networks:
      - datafluxfunc
      - default
    command: ./run-worker.sh
  # WORKER MINI END

  beat:
    image: <DATAFLUX_FUNC_IMAGE>
    labels:
      - beat
    volumes:
      - "<INSTALL_DIR>/data:/data"
    networks:
      - datafluxfunc
      - default
    command: ./run-beat.sh

  server:
    image: <DATAFLUX_FUNC_IMAGE>
    labels:
      - server
    volumes:
      - "<INSTALL_DIR>/data:/data"
    networks:
      - datafluxfunc
      - default
    ports:
      - "8088:8088"
    command: ./run-server.sh

networks:
  default:
    external:
      name: bridge
  datafluxfunc:
    driver: overlay
