<i18n locale="en" lang="yaml">
lastSucceeded : 'Succeeded {t}'
lastFailed    : 'Failed {t}'
lastRan       : 'Ran {t}'
successCount  : 'Success {n}'
failureCount  : 'Failure {n}'
</i18n>

<i18n locale="zh-CN" lang="yaml">
Jump to...                                     : 跳转到...
Refresh                                        : 刷新列表
New Script                                     : 新建脚本
New Script Set                                 : 新建脚本集
Edited                                         : 已修改
Locked by other user ({user})                  : 被其他用户（{user}）锁定
Locked by you                                  : 被您锁定
Quick View                                     : 快速查看
View                                           : 查看
Setup                                          : 配置
Example (In Same Script Set)                   : 示例（在相同脚本集中）
Example (In Other Script Set)                  : 示例（在其他脚本集中）
Copy {name} ID                                 : 复制{name} ID
Code edited but not published yet              : 代码已修改但尚未发布
'Import/Calling will run the published version': 引用 / API 调用实际将运行已发布代码
Export Script Set                              : 导出脚本集
'Assigned to queue #{queue}'                   : '指派到队列 #{queue}'
Script Set {id}: 脚本集 {id}
Script {id}    : 脚本 {id}

Please input ID                                   : 请输入 ID
Script Set ID too long                            : 脚本集 ID 过长
Only alphabets, numbers and underscore are allowed: 只能包含大小写英文、数字及下划线
Cannot not starts with a number                   : 不得以数字开头
Please input new Script Set ID                    : 请输入新脚本集 ID
Inputed Script Set ID already exists              : 输入的脚本集 ID 已经存在

Script Set pinned  : 脚本集已置顶
Script Set unpinned: 脚本集已取消
Script Set locked  : 脚本集已上锁
Script Set unlocked: 脚本集已解锁
Script Set cloned  : 脚本集已克隆
Script Set exported: 脚本集已导出
Script Set deleted : 脚本集已删除
Script locked      : 脚本已上锁
Script unlocked    : 脚本已解锁
Script deleted     : 脚本已删除

Installed form Script Market      : 从脚本市场安装的脚本集
The Script Market has been removed: 脚本市场已被删除

Config    : 配置
Auth      : 认证
Cron Expr : Cron 表达式
Expires   : 过期
Throttling: 限流
Created   : 创建
Run       : 执行

Sync API List : 同步 API 列表
Async API List: 异步 API 列表
Cron Job List : 定时任务列表

lastSucceeded : '{t}调用成功'
lastFailed    : '{t}调用失败'
lastRan       : '{t}调用'
successCount  : '成功 {n}'
failureCount  : '失败 {n}'

Are you sure you want to delete the Script Set?<br><strong class="text-bad">{label}</strong>: 是否确认删除此脚本集?<br><strong class="text-bad">{label}</strong>
Are you sure you want to delete the Script?<br><strong class="text-bad">{label}</strong>: 是否确认删除此脚本<br><strong class="text-bad">{label}</strong>
Are you sure you want to start the Cron Job manually?: 是否确认手动启动此定时任务？
Cron Job Started Manually: 定时任务已手工启动

Sync, Async APIs and Cron Jobs: 同步、异步 API 和定时任务
Go to Recent Task Record      : 前往最近任务记录
Go to Script Market           : 前往脚本市场

Some Script Sets have been hidden: 一些脚本集已被隐藏
"In most cases, the Script Sets that users doesn't need to care about are hidden by default.": "大多数情况下，用户不需要关心的脚本集默认会被隐藏。"
"You can change the default behavior in [Management / System Settings]."                     : "您可以在「管理 / 系统设置」中修改默认此行为。"
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Are you sure you want to delete the Script Set?<br><strong class="text-bad">{label}</strong>: 是否確認刪除此腳本集?<br><strong class="text-bad">{label}</strong>
Are you sure you want to delete the Script?<br><strong class="text-bad">{label}</strong>: 是否確認刪除此腳本<br><strong class="text-bad">{label}</strong>
Are you sure you want to start the Cron Job manually?: 是否確認手動啓動此定時任務？
'Assigned to queue #{queue}': '指派到隊列 #{queue}'
Async API List: 異步 API 列表
Auth: 認證
Cannot not starts with a number: 不得以數字開頭
Code edited but not published yet: 代碼已修改但尚未發佈
Config: 配置
Copy {name} ID: 複製{name} ID
Created: 創建
Cron Expr: Cron 表達式
Cron Job List: 定時任務列表
Cron Job Started Manually: 定時任務已手工啓動
Edited: 已修改
Example (In Other Script Set): 示例（在其他腳本集中）
Example (In Same Script Set): 示例（在相同腳本集中）
Expires: 過期
Export Script Set: 導出腳本集
Go to Recent Task Record: 前往最近任務記錄
Go to Script Market: 前往腳本市場
Import/Calling will run the published version: 引用 / API 調用實際將運行已發佈代碼
In most cases, the Script Sets that users doesn't need to care about are hidden by default.: 大多數情況下，用户不需要關心的腳本集默認會被隱藏。
Inputed Script Set ID already exists: 輸入的腳本集 ID 已經存在
Installed form Script Market: 從腳本市場安裝的腳本集
Jump to...: 跳轉到...
Locked by other user ({user}): 被其他用户（{user}）鎖定
Locked by you: 被您鎖定
New Script: 新建腳本
New Script Set: 新建腳本集
Only alphabets, numbers and underscore are allowed: 只能包含大小寫英文、數字及下劃線
Please input ID: 請輸入 ID
Please input new Script Set ID: 請輸入新腳本集 ID
Quick View: 快速查看
Refresh: 刷新列表
Run: 執行
Script Set ID too long: 腳本集 ID 過長
Script Set cloned: 腳本集已克隆
Script Set deleted: 腳本集已刪除
Script Set exported: 腳本集已導出
Script Set locked: 腳本集已上鎖
Script Set pinned: 腳本集已置頂
Script Set unlocked: 腳本集已解鎖
Script Set unpinned: 腳本集已取消
Script Set {id}: 腳本集 {id}
Script deleted: 腳本已刪除
Script locked: 腳本已上鎖
Script unlocked: 腳本已解鎖
Script {id}: 腳本 {id}
Setup: 配置
Some Script Sets have been hidden: 一些腳本集已被隱藏
Sync API List: 同步 API 列表
Sync, Async APIs and Cron Jobs: 同步、異步 API 和定時任務
The Script Market has been removed: 腳本市場已被刪除
Throttling: 限流
View: 查看
You can change the default behavior in [Management / System Settings].: 您可以在「管理 / 系統設置」中修改默認此行為。
failureCount: 失敗 {n}
lastFailed: '{t}調用失敗'
lastRan: '{t}調用'
lastSucceeded: '{t}調用成功'
successCount: 成功 {n}
</i18n>
<i18n locale="zh-TW" lang="yaml">
Are you sure you want to delete the Script Set?<br><strong class="text-bad">{label}</strong>: 是否確認刪除此指令碼集?<br><strong class="text-bad">{label}</strong>
Are you sure you want to delete the Script?<br><strong class="text-bad">{label}</strong>: 是否確認刪除此指令碼<br><strong class="text-bad">{label}</strong>
Are you sure you want to start the Cron Job manually?: 是否確認手動啟動此定時任務？
'Assigned to queue #{queue}': '指派到佇列 #{queue}'
Async API List: 非同步 API 列表
Auth: 認證
Cannot not starts with a number: 不得以數字開頭
Code edited but not published yet: 程式碼已修改但尚未釋出
Config: 配置
Copy {name} ID: 複製{name} ID
Created: 建立
Cron Expr: Cron 表示式
Cron Job List: 定時任務列表
Cron Job Started Manually: 定時任務已手工啟動
Edited: 已修改
Example (In Other Script Set): 示例（在其他指令碼集中）
Example (In Same Script Set): 示例（在相同指令碼集中）
Expires: 過期
Export Script Set: 匯出指令碼集
Go to Recent Task Record: 前往最近任務記錄
Go to Script Market: 前往指令碼市場
Import/Calling will run the published version: 引用 / API 呼叫實際將執行已釋出程式碼
In most cases, the Script Sets that users doesn't need to care about are hidden by default.: 大多數情況下，使用者不需要關心的指令碼集預設會被隱藏。
Inputed Script Set ID already exists: 輸入的指令碼集 ID 已經存在
Installed form Script Market: 從指令碼市場安裝的指令碼集
Jump to...: 跳轉到...
Locked by other user ({user}): 被其他使用者（{user}）鎖定
Locked by you: 被您鎖定
New Script: 新建指令碼
New Script Set: 新建指令碼集
Only alphabets, numbers and underscore are allowed: 只能包含大小寫英文、數字及下劃線
Please input ID: 請輸入 ID
Please input new Script Set ID: 請輸入新指令碼集 ID
Quick View: 快速檢視
Refresh: 重新整理列表
Run: 執行
Script Set ID too long: 指令碼集 ID 過長
Script Set cloned: 指令碼集已克隆
Script Set deleted: 指令碼集已刪除
Script Set exported: 指令碼集已匯出
Script Set locked: 指令碼集已上鎖
Script Set pinned: 指令碼集已置頂
Script Set unlocked: 指令碼集已解鎖
Script Set unpinned: 指令碼集已取消
Script Set {id}: 指令碼集 {id}
Script deleted: 指令碼已刪除
Script locked: 指令碼已上鎖
Script unlocked: 指令碼已解鎖
Script {id}: 指令碼 {id}
Setup: 配置
Some Script Sets have been hidden: 一些指令碼集已被隱藏
Sync API List: 同步 API 列表
Sync, Async APIs and Cron Jobs: 同步、非同步 API 和定時任務
The Script Market has been removed: 指令碼市場已被刪除
Throttling: 限流
View: 檢視
You can change the default behavior in [Management / System Settings].: 您可以在「管理 / 系統設定」中修改預設此行為。
failureCount: 失敗 {n}
lastFailed: '{t}呼叫失敗'
lastRan: '{t}呼叫'
lastSucceeded: '{t}呼叫成功'
successCount: 成功 {n}
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <div id="aside-script-content" class="aside-inner-content">
    <div class="jump-to-select-wrap">
      <el-select class="jump-to-select"
        :placeholder="$t('Jump to...')"
        :no-data-text="$t('No Data')"
        size="small"
        clearable
        filterable
        :filter-method="T.debounce(doFilter)"
        v-model="selectFilterText">
        <el-option
          v-for="item in selectShowOptions"
          :key="item.id"
          :label="item.label"
          :value="item.id">
          <span class="select-item-name">
            <i v-if="item.type === 'scriptSet'" class="fa fa-fw fa-folder"></i>
            <i v-else-if="item.type === 'script'" class="fa fa-fw fa-file-code-o"></i>
            <el-tag v-else-if="item.type === 'func'" type="info" size="mini"><code>def</code></el-tag>
            {{ item.label }}
          </span>
          <code class="select-item-id code-font">ID: {{ item.id }}</code>
        </el-option>
      </el-select>
    </div>

    <el-tree class="aside-tree"
      v-loading="loading"
      :data="data"
      :highlight-current="true"
      :default-expand-all="false"
      :default-expanded-keys="defaultExpandedNodeKeys"
      :auto-expand-parent="false"
      :expand-on-click-node="false"
      :indent="10"
      node-key="id"
      v-on:node-expand="onExpandNode"
      v-on:node-collapse="onCollapseNode"
      ref="tree">

      <span
        slot-scope="{node, data}"
        class="aside-tree-node"
        :entry-id="data.id"
        @click="openEntity(data)">

        <!-- 菜单 -->
        <el-popover
          placement="right-start"
          trigger="hover"
          popper-class="aside-tip"
          :disabled="!data.id && !data.tip"
          v-model="data.showPopover">

          <div slot="reference" class="aside-item">
            <!-- 项目内容 -->
            <span :class="{'text-watch': data.origin === 'builtin', 'text-main': data.origin === 'scriptMarket', 'text-bad': data.isPinned}">
              <el-link v-if="data.type === 'refresh'" type="primary">
                <i class="fa fa-fw fa-refresh"></i> {{ $t('Refresh') }}
              </el-link>
              <el-link v-else-if="data.type === 'addScriptSet'" type="primary">
                <i class="fa fa-fw fa-plus"></i> {{ $t('New Script Set') }}
              </el-link>
              <el-link v-else-if="data.type === 'scriptSetHiddenTip'" type="info">
                <i class="fa fa-fw fa-eye-slash"></i> <i>{{ $t('Some Script Sets have been hidden') }}</i>
              </el-link>
              <div v-else>
                <template v-if="data.type === 'scriptSet'">
                  <i v-if="data.origin === 'builtin'" class="fa fa-fw fa-microchip"></i>
                  <i v-else-if="data.origin === 'scriptMarket'" class="fa fa-fw fa-shopping-cart"></i>
                  <i v-else-if="data.origin === 'blueprint'" class="fa fa-fw fa-sitemap fa-rotate-270"></i>
                  <i v-else class="fa fa-fw" :class="[node.expanded ? 'fa-folder-open':'fa-folder']"></i>
                </template>
                <i v-else-if="data.type === 'script'" class="fa fa-fw fa-file-code-o"></i>
                <el-tag v-else-if="data.type === 'func'" type="info" size="mini"><code>def</code></el-tag>

                <el-tag v-if="data.isCodeEdited"
                  type="danger"
                  size="mini">{{ $t('Edited') }}</el-tag>
                <span>{{ node.label }}</span>
              </div>
            </span>

            <!-- 状态图标 -->
            <div>
              <el-tooltip v-if="data.type === 'func' && T.notNothing(data.queue)"
                effect="dark" :content="$t('Assigned to queue #{queue}', { queue: data.queue})" placement="top" :enterable="false">
                <el-tag size="mini">#{{ data.queue }}</el-tag>
              </el-tooltip>
              <el-tooltip v-if="data.isLocked"
                effect="dark" :content="data.isLockedByOther ? $t('Locked by other user ({user})', { user: data.lockedByUser }) : $t('Locked by you')" placement="top" :enterable="false">
                <i class="fa fa-fw fa-lock" :class="(data.isLockedByOther ? 'text-bad' : 'text-good') + (data.isLockedByScriptSet ? '-fade text-small' : '')"></i>
              </el-tooltip>
              <el-tooltip v-if="data.isPinned"
                effect="dark" :content="$t('Pinned')" placement="top" :enterable="false">
                <i class="fa fa-fw fa-thumb-tack text-bad"></i>
              </el-tooltip>
            </div>
          </div>

          <!-- 提示 -->
          <div v-if="data.tip" class="aside-tree-node-tip">
            <i class="fa fa-fw fa-info-circle"></i> <strong v-if="data.tipTitle">{{ data.tipTitle }}<br></strong>
            <span v-html="data.tip" />
          </div>

          <!-- 基本信息 -->
          <div v-if="data.id" class="aside-tree-node-description">
            <InfoBlock type="warning" v-if="data.origin === 'builtin'" :title="$t('Built-in Script Set')" />
            <InfoBlock type="warning" v-if="data.origin === 'scriptMarket'" :title="$t('Installed form Script Market')" />

            <span class="text-info">ID</span>
            &nbsp;<code class="text-main">{{ data.id }}</code>
            <CopyButton :content="data.id" />

            <pre v-if="(data.type === 'scriptSet' || data.type === 'script') && data.description">{{ data.description }}</pre>
          </div>

          <!-- 示例代码 -->
          <template v-if="data.sampleCodeImportFromSameScriptSet">
            <div class="aside-tree-node-sample">
              <span class="text-info">{{ $t('Example (In Same Script Set)') }}</span>
              <CopyButton :content="data.sampleCodeImportFromSameScriptSet" />

              <pre>{{ data.sampleCodeImportFromSameScriptSet }}</pre>
            </div>
          </template>
          <template v-if="data.sampleCodeImportFromOtherScriptSet">
            <div class="aside-tree-node-sample">
              <span class="text-info">{{ $t('Example (In Other Script Set)') }}</span>
              <CopyButton :content="data.sampleCodeImportFromOtherScriptSet" />

              <pre>{{ data.sampleCodeImportFromOtherScriptSet }}</pre>
            </div>
          </template>

          <!-- 已编辑提示 -->
          <template v-if="data.isCodeEdited">
            <br>
            <div class="code-edited-tip">
              <span class="text-bad">{{ $t('Code edited but not published yet') }}<br>{{ $t('Import/Calling will run the published version') }}</span>
            </div>
          </template>

          <!-- 操作 -->
          <template v-if="[ 'scriptSet', 'script', 'func' ].indexOf(data.type) >= 0">
            <template v-if="[ 'scriptSet', 'script' ].indexOf(data.type) >= 0">
              <br>

              <el-button-group>
                <!-- 添加脚本（脚本集） -->
                <el-button v-if="data.type === 'scriptSet'"
                  size="small"
                  :disabled="!data.isEditable"
                  @click="openEntity(data, 'add')">
                  <i class="fa fa-fw fa-plus"></i>
                  {{ $t('New Script') }}
                </el-button>

                <!-- 添加脚本（脚本） -->
                <el-button v-if="data.type === 'script'"
                  size="small"
                  :disabled="!(scriptSetMap[data.scriptSetId] || {}).isEditable"
                  @click="openEntity(data, 'add')">
                  <i class="fa fa-fw fa-plus"></i>
                  {{ $t('New Script') }}
                </el-button>

                <!-- 配置 -->
                <el-button
                  size="small"
                  @click="openEntity(data, 'setup')">
                  <i class="fa fa-fw fa-wrench"></i>
                  {{ $t('Setup') }}
                </el-button>
              </el-button-group>

              <el-button-group>
                <!-- 快速查看 -->
                <el-button v-if="data.type === 'script'"
                  size="small"
                  @click="showQuickViewWindow(data)">
                  <i class="fa fa-fw fa-window-restore"></i>
                  {{ $t('Quick View') }}
                </el-button>

                <!-- 置顶 -->
                <el-button v-if="data.type === 'scriptSet'"
                  size="small"
                  :class="data.isPinned ? 'aside-on-button' : ''"
                  :disabled="!data.isEditable"
                  v-prevent-re-click @click="pinData(data.type, data.id, !data.isPinned)">
                  <i class="fa fa-fw" :class="[data.isPinned ? 'fa-thumb-tack fa-rotate-270' : 'fa-thumb-tack']"></i>
                  {{ data.isPinned ? $t('Unpin') : $t('Pin') }}
                </el-button>

                <!-- 锁定/解锁脚本/脚本集 -->
                <el-button
                  size="small"
                  :class="data.isLocked ? 'aside-on-button' : ''"
                  :disabled="!data.isEditable || (data.type === 'script' && data.isLockedByScriptSet)"
                  v-prevent-re-click @click="lockData(data.type, data.id, !data.isLocked)">
                  <i class="fa fa-fw" :class="[data.isLocked ? 'fa-unlock' : 'fa-lock']"></i>
                  {{ data.isLocked ? $t('Unlock') : $t('Lock') }}
                </el-button>

                <!-- 克隆 -->
                <el-button v-if="data.type === 'scriptSet'"
                  size="small"
                  @click="cloneData(data)">
                  <i class="fa fa-fw fa-files-o"></i>
                  {{ $t('Clone') }}
                </el-button>

                <!-- 导出 -->
                <el-button v-if="data.type === 'scriptSet'"
                  size="small"
                  @click="exportData(data)">
                  <i class="fa fa-fw fa-cloud-download"></i>
                  {{ $t('Export') }}
                </el-button>
              </el-button-group>

              <el-button-group>
                <!-- 删除 -->
                <el-button
                  class="danger-button"
                  size="small"
                  :disabled="!data.isEditable"
                  @click="deleteEntity(data)">
                  <i class="fa fa-fw fa-times"></i>
                  {{ $t('Delete') }}
                </el-button>
              </el-button-group>
            </template>

            <!-- 关联信息 -->
            <div class="goto-links">
              <!-- 同步、异步 API 和定时任务 -->
              <el-link v-if="data.type === 'func'"
                @click="openRelEntity(node, data, 'syncAPI')">
                <i class="fa fa-fw fa-window-restore"></i>
                {{ $t('Sync, Async APIs and Cron Jobs') }}
              </el-link>

              <!-- 前往任务记录 -->
              <el-link v-if="data.type === 'func'"
                @click="common.goToTaskRecord({ funcId: data.id })">
                <i class="fa fa-fw fa-share-square"></i>
                {{ $t('Go to Recent Task Record') }}
              </el-link>

              <!-- 前往脚本市场 -->
              <el-tooltip effect="dark" :disabled="!!data.scriptMarketId" :content="$t('The Script Market has been removed')" placement="right">
                <el-link v-if="data.origin === 'scriptMarket' && data.originId"
                  :disabled="!data.scriptMarketId"
                  @click="openEntity(data, 'scriptMarket')">
                  <i class="fa fa-fw fa-share-square"></i>
                  {{ $t('Go to Script Market') }}
                </el-link>
              </el-tooltip>
            </div>
          </template>
        </el-popover>
      </span>
    </el-tree>

    <QuickViewWindow ref="quickViewWindow"></QuickViewWindow>

    <APIExampleDialog ref="apiExampleDialog"></APIExampleDialog>

    <ScriptSetSetup ref="ScriptSetSetup" />
    <ScriptSetup ref="ScriptSetup" />

    <el-dialog
      :visible.sync="showRelEntity"
      width="1050px">
      <div slot="title">
        <FuncInfo
          :id="relEntityFunc.id"
          :title="relEntityFunc.title"
          :definition="relEntityFunc.definition"
          :hideGotoFunc="true" />
        <span class="text-info press-esc-to-close-tip">{{ $t('Press ESC to close') }}</span>
      </div>
      <el-tabs v-model="relEntityTarget">
        <el-tab-pane name="syncAPI">
          <span slot="label"><i class="fa fa-fw fa-link"></i> {{ $t('Sync API') }}</span>

          <transition name="fade">
          <el-table
            class="common-table" v-if="showRelEntityData"
            :data="relEntities.syncAPIs">
            <el-table-column :label="$t('Sync API')">
              <template slot-scope="scope">
                <span class="text-info">ID</span>
                &nbsp;<code class="text-main">{{ scope.row.id }}</code>
                <CopyButton :content="scope.row.id" />

                <template v-if="scope.row.note">
                  <br>
                  <span class="text-info">&#12288;{{ $t('Note') }}{{ $t(':') }}</span>
                  <span>{{ scope.row.note }}</span>
                </template>
              </template>
            </el-table-column>

            <el-table-column :label="$t('Config')" width="220">
              <template slot-scope="scope">
                <span class="text-info">{{ $t('Auth') }}{{ $t(':') }}</span>
                <el-tooltip :content="scope.row.apia_title" :disabled="!!!scope.row.apia_title" placement="right">
                  <span :class="{ 'text-main': !!scope.row.apia_id }">{{ C.API_AUTH_MAP.get(scope.row.apia_type).name }}</span>
                </el-tooltip>

                <br>
                <span class="text-info">{{ $t('Expires') }}{{ $t(':') }}</span>
                <span v-if="!scope.row.expireTime">-</span>
                <template v-else>
                  <RelativeDateTime :datetime="scope.row.expireTime"
                    :class="T.isExpired(scope.row.expireTime) ? 'text-bad' : 'text-good'" />
                </template>

                <br>
                <span class="text-info">{{ $t('Throttling') }}{{ $t(':') }}</span>
                <span v-if="T.isNothing(scope.row.throttlingJSON)">-</span>
                <el-tooltip v-else placement="right">
                  <div slot="content">
                    <template v-for="opt in C.SYNC_API_THROTTLING">
                      <span v-if="scope.row.throttlingJSON[opt.key]">{{ $tc(opt.name, scope.row.throttlingJSON[opt.key]) }}<br></span>
                    </template>
                  </div>
                  <span class="text-bad">{{ $t('ON') }}</span>
                </el-tooltip>
              </template>
            </el-table-column>

            <el-table-column :label="$t('Status')" width="220">
              <template slot-scope="scope">
                <span v-if="scope.row.isDisabled" class="text-bad"><i class="fa fa-fw fa-ban"></i> {{ $t('Disabled') }}</span>
                <span v-else class="text-good"><i class="fa fa-fw fa-check"></i> {{ $t('Enabled') }}</span>

                <template v-if="scope.row.lastStartTime">
                  <br>
                  <span v-if="scope.row.lastStatus === 'success'" class="text-good">
                    <i class="fa fa-fw fa-check"></i> {{ $t('lastSucceeded', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>
                  <span v-else-if="scope.row.lastStatus === 'failure'" class="text-bad">
                    <i class="fa fa-fw fa-times"></i> {{ $t('lastFailed', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>
                  <span v-else class="text-main">
                    <i class="fa fa-fw fa-clock-o"></i> {{ $t('lastRan', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>

                  <br>
                  <i class="fa fa-fw fa-pie-chart text-info"></i>
                  <span :class="{ 'text-good': !!scope.row.recentSuccessCount }">{{ $t('successCount', { n: T.numberLimit(scope.row.recentSuccessCount) }) }}</span>
                  / <span :class="{ 'text-bad': !!scope.row.recentFailureCount }">{{ $t('failureCount', { n: T.numberLimit(scope.row.recentFailureCount) }) }}</span>
                </template>
              </template>
            </el-table-column>

            <el-table-column align="right" width="180">
              <template slot="header" slot-scope="scope">
                <el-link type="primary" @click="$router.push({name: 'sync-api-list'})">
                  {{ $t('Sync API List') }}
                  <i class="fa fa-fw fa-share-square"></i>
                </el-link>
              </template>
              <template slot-scope="scope">
                <el-link :disabled="T.isNothing(scope.row.func_id)" @click="showAPI(scope.row, '/api/v1/sync/:id')">{{ $t('Example') }}</el-link>
              </template>
            </el-table-column>
          </el-table>
          </transition>
        </el-tab-pane>

        <el-tab-pane name="asyncAPI">
          <span slot="label"><i class="fa fa-fw fa-tasks"></i> {{ $t('Async API') }}</span>

          <transition name="fade">
          <el-table
            class="common-table" v-if="showRelEntityData"
            :data="relEntities.asyncAPIs">
            <el-table-column :label="$t('Async API')">
              <template slot-scope="scope">
                <span class="text-info">ID</span>
                &nbsp;<code class="text-main">{{ scope.row.id }}</code>
                <CopyButton :content="scope.row.id" />

                <template v-if="scope.row.note">
                  <br>
                  <span class="text-info">&#12288;{{ $t('Note') }}{{ $t(':') }}</span>
                  <span>{{ scope.row.note }}</span>
                </template>
              </template>
            </el-table-column>

            <el-table-column :label="$t('Config')" width="220">
              <template slot-scope="scope">
                <span class="text-info">{{ $t('Auth') }}{{ $t(':') }}</span>
                <el-tooltip :content="scope.row.apia_title" :disabled="!!!scope.row.apia_title" placement="right">
                  <span :class="{ 'text-main': !!scope.row.apia_id }">{{ C.API_AUTH_MAP.get(scope.row.apia_type).name }}</span>
                </el-tooltip>
              </template>
            </el-table-column>

            <el-table-column :label="$t('Status')" width="220">
              <template slot-scope="scope">
                <span v-if="scope.row.isDisabled" class="text-bad"><i class="fa fa-fw fa-ban"></i> {{ $t('Disabled') }}</span>
                <span v-else class="text-good"><i class="fa fa-fw fa-check"></i> {{ $t('Enabled') }}</span>

                <template v-if="scope.row.lastStartTime">
                  <br>
                  <span v-if="scope.row.lastStatus === 'success'" class="text-good">
                    <i class="fa fa-fw fa-check"></i> {{ $t('lastSucceeded', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>
                  <span v-else-if="scope.row.lastStatus === 'failure'" class="text-bad">
                    <i class="fa fa-fw fa-times"></i> {{ $t('lastFailed', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>
                  <span v-else class="text-main">
                    <i class="fa fa-fw fa-clock-o"></i> {{ $t('lastRan', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>

                  <br>
                  <i class="fa fa-fw fa-pie-chart text-info"></i>
                  <span :class="{ 'text-good': !!scope.row.recentSuccessCount }">{{ $t('successCount', { n: T.numberLimit(scope.row.recentSuccessCount) }) }}</span>
                  / <span :class="{ 'text-bad': !!scope.row.recentFailureCount }">{{ $t('failureCount', { n: T.numberLimit(scope.row.recentFailureCount) }) }}</span>
                </template>
              </template>
            </el-table-column>

            <el-table-column align="right" width="180">
              <template slot="header" slot-scope="scope">
                <el-link type="primary" @click="$router.push({name: 'async-api-list'})">
                  {{ $t('Async API List') }}
                  <i class="fa fa-fw fa-share-square"></i>
                </el-link>
              </template>
              <template slot-scope="scope">
                <el-link :disabled="T.isNothing(scope.row.func_id)" @click="showAPI(scope.row, '/api/v1/async/:id')">{{ $t('Example') }}</el-link>
              </template>
            </el-table-column>
          </el-table>
          </transition>
        </el-tab-pane>

        <el-tab-pane name="cronJob">
          <span slot="label"><i class="fa fa-fw fa-clock-o"></i> {{ $t('Cron Job') }}</span>

          <transition name="fade">
          <el-table
            class="common-table" v-if="showRelEntityData"
            :data="relEntities.cronJobs">
            <el-table-column :label="$t('Cron Job')">
              <template slot-scope="scope">
                <span class="text-info">ID</span>
                &nbsp;<code class="text-main">{{ scope.row.id }}</code>
                <CopyButton :content="scope.row.id" />

                <template v-if="scope.row.note">
                  <br>
                  <span class="text-info">&#12288;{{ $t('Note') }}{{ $t(':') }}</span>
                  <span>{{ scope.row.note }}</span>
                </template>
              </template>
            </el-table-column>

            <el-table-column :label="$t('Config')" width="220">
              <template slot-scope="scope">
                <span class="text-info">{{ $t('Cron Expr') }}{{ $t(':') }}</span>
                <template v-if="scope.row.func_extraConfigJSON && scope.row.func_extraConfigJSON.fixedCronExpr">
                  <code class="text-main">{{ scope.row.func_extraConfigJSON.fixedCronExpr }}</code>
                  <el-tag size="mini">{{ $t('Fixed') }}</el-tag>
                </template>
                <code v-else-if="scope.row.cronExpr" class="text-main">{{ scope.row.cronExpr }}</code>
                <span v-else class="text-bad">{{ $t('Not Set') }}</span>

                <br>
                <span class="text-info">{{ $t('Created') }}{{ $t(':') }}</span>
                <RelativeDateTime :datetime="scope.row.createTime" />

                <br>
                <span class="text-info">{{ $t('Expires') }}{{ $t(':') }}</span>
                <span v-if="!scope.row.expireTime">-</span>
                <template v-else>
                  <RelativeDateTime :datetime="scope.row.expireTime"
                    :class="T.isExpired(scope.row.expireTime) ? 'text-bad' : 'text-good'" />
                </template>
              </template>
            </el-table-column>

            <el-table-column :label="$t('Status')" width="220">
              <template slot-scope="scope">
                <span v-if="scope.row.isDisabled" class="text-bad"><i class="fa fa-fw fa-ban"></i> {{ $t('Disabled') }}</span>
                <span v-else class="text-good"><i class="fa fa-fw fa-check"></i> {{ $t('Enabled') }}</span>

                <template v-if="scope.row.lastStartTime">
                  <br>
                  <span v-if="scope.row.lastStatus === 'success'" class="text-good">
                    <i class="fa fa-fw fa-check"></i> {{ $t('lastSucceeded', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>
                  <span v-else-if="scope.row.lastStatus === 'failure'" class="text-bad">
                    <i class="fa fa-fw fa-times"></i> {{ $t('lastFailed', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>
                  <span v-else class="text-main">
                    <i class="fa fa-fw fa-clock-o"></i> {{ $t('lastRan', { t: T.fromNow(scope.row.lastStartTime) }) }}
                  </span>

                  <br>
                  <i class="fa fa-fw fa-pie-chart text-info"></i>
                  <span :class="{ 'text-good': !!scope.row.recentSuccessCount }">{{ $t('successCount', { n: T.numberLimit(scope.row.recentSuccessCount) }) }}</span>
                  / <span :class="{ 'text-bad': !!scope.row.recentFailureCount }">{{ $t('failureCount', { n: T.numberLimit(scope.row.recentFailureCount) }) }}</span>
                </template>
              </template>
            </el-table-column>

            <el-table-column align="right" width="180">
              <template slot="header" slot-scope="scope">
                <el-link type="primary" @click="$router.push({name: 'cron-job-list'})">
                  {{ $t('Cron Job List') }}
                  <i class="fa fa-fw fa-share-square"></i>
                </el-link>
              </template>
              <template slot-scope="scope">
                <el-link @click="startCronJobManually(scope.row)" :disabled="!scope.row.func_id">
                  {{ $t('Run') }}
                </el-link>
              </template>
            </el-table-column>
          </el-table>
          </transition>
        </el-tab-pane>
      </el-tabs>
    </el-dialog>
  </div>
</template>

<script>
import QuickViewWindow from '@/components/Development/QuickViewWindow'
import APIExampleDialog from '@/components/APIExampleDialog'

import FileSaver from 'file-saver';

import ScriptSetSetup from '@/components/Development/ScriptSetSetup'
import ScriptSetup from '@/components/Development/ScriptSetup'

export default {
  name: 'AsideScript',
  components: {
    QuickViewWindow,
    APIExampleDialog,

    ScriptSetSetup,
    ScriptSetup,
  },
  watch: {
    selectFilterText(val) {
      if (!val) return;
      if (!this.$refs.tree) return;

      let node = this.$refs.tree.getNode(val);
      this.openEntity(node.data);
    },
    '$store.state.scriptListSyncTime': function() {
      this.loadData();
    },
    expandedNodeMap(val) {
      // 自动记录已展开的节点
      this.$store.commit('updateAsideScript_expandedNodeMap', val);
    },
    relEntityTarget(val) {
      this.showRelEntityData = false;
      this.$nextTick(() => {
        this.showRelEntityData = true;
      });
    },
  },
  methods: {
    doFilter(q) {
      q = (q || '').toLowerCase().trim();
      if (!q) {
        this.selectShowOptions = this.selectOptions;
      } else {
        this.selectShowOptions = this.T.filterByKeywords(q, this.selectOptions);
      }
    },

    // 展开/收起节点
    onExpandNode(data, node) {
      this.$set(this.expandedNodeMap, data.id, true);
    },
    onCollapseNode(data, node) {
      this.$delete(this.expandedNodeMap, data.id);
    },

    // 选中节点
    selectNode(nodeKey, options) {
      options = options || {};

      if (!this.$refs.tree) return;
      if (!nodeKey) return;

      setImmediate(() => {
        let node = this.$refs.tree.getNode(nodeKey);
        if (!node || !node.data) return;

        // 选中
        this.$refs.tree.setCurrentKey(node.data.id);

        // 展开所有父层
        let parentNode = node.parent;
        while (parentNode) {
          parentNode.expand();
          this.onExpandNode(parentNode.data, parentNode);

          parentNode = parentNode.parent;
        }

        // 展开当前节点
        if (options.expandChildren) {
          node.expand();
          this.onExpandNode(node.data, node);
        }

        setTimeout(() => {
          // 滚动到目标位置
          let $asideContent = document.getElementById('aside-script-content');
          let $target = document.querySelector(`[entry-id="${node.data.id}"]`);
          if (!$target) return;

          let scrollTop = 0;
          let topPadding = 35;
          if ($asideContent.scrollTop + topPadding > $target.offsetTop) {
            scrollTop = $target.offsetTop - topPadding;
          } else if ($asideContent.scrollTop + $asideContent.offsetHeight < $target.offsetTop) {
            scrollTop = $target.offsetTop - $asideContent.offsetHeight + $target.offsetHeight;
          } else {
            return;
          }
          $asideContent.scrollTo({ top: scrollTop, behavior: 'smooth' });
        }, 300);
      });
    },
    async loadData() {
      if (this.T.isNothing(this.data)) {
        this.loading = true;
      }

      // 节点实体表。主要用于判断业务实体是否存在，结构为：{ "<ID>": "scriptSet|script|func" }
      let nodeEntity = {};

      // 脚本集/脚本/函数表。结构为：{ "<ID>": {JSON Data} }
      let scriptSetMap = {};
      let scriptMap    = {};
      let funcMap      = {};

      /***** 脚本集 *****/
      let hasHiddenScripts = false;
      let apiRes = await this.T.callAPI_getAll('/api/v1/script-sets/do/list', {
        query: {
          fields: [
            'id',
            'title',
            'description',
            'lockedByUserId',
            'lockedByUserUsername',
            'lockedByUserName',
            'origin',
            'originId',
            'pinTime',
            'smkt_id',
          ]
        },
      });
      if (!apiRes || !apiRes.ok) return;

      apiRes.data.forEach(d => {
        // 跳过隐藏的脚本集
        if (this.common.shouldScriptSetHidden(d)) {
          hasHiddenScripts = true;
          return;
        }

        // 记录节点
        nodeEntity[d.id] = 'scriptSet';

        // 缩减描述行数
        d.description = this.T.limitLines(d.description, 10);

        // 创建节点数据
        let lockedByUser    = `${d.lockedByUserName || d.lockedByUsername || this.$t('UNKNOWN')}`;
        let isLockedByMe    = d.lockedByUserId === this.$store.getters.userId;
        let isLockedByOther = d.lockedByUserId && !isLockedByMe;
        let isEditable      = this.$store.getters.isAdmin || !isLockedByOther;
        let isLocked        = isLockedByMe || isLockedByOther;
        let isPinned        = !!d.pinTime;
        scriptSetMap[d.id] = {
          id             : d.id,
          label          : d.title || d.id,
          type           : 'scriptSet',
          lockedByUser   : lockedByUser,
          isLockedByMe   : isLockedByMe,
          isLockedByOther: isLockedByOther,
          isEditable     : isEditable,
          isLocked       : isLocked,
          isPinned       : isPinned,
          pinTime        : d.pinTime,
          origin         : d.origin,
          originId       : d.originId,
          scriptMarketId : d.smkt_id,

          title      : d.title,
          description: d.description,

          children   : [],
          showPopover: false,
        };
        this.T.appendSearchFields(scriptSetMap[d.id], ['id', 'title'])
      });

      /***** 脚本 *****/
      apiRes = await this.T.callAPI_getAll('/api/v1/scripts/do/list', {
        query: {
          fields: [
            'id',
            'title',
            'description',
            'scriptSetId',
            'codeMD5',
            'codeDraftMD5',
            'lockedByUserId',
            'lockedByUserUsername',
            'lockedByUserName',
            'sset_lockedByUserId',
            'sset_lockedByUserUsername',
            'sset_lockedByUserName',
          ]
        },
      });
      if (!apiRes || !apiRes.ok) return;

      window._DFF_scriptIds = [];
      apiRes.data.forEach(d => {
        // 跳过不存在的脚本集
        if (!scriptSetMap[d.scriptSetId]) return;

        window._DFF_scriptIds.push(d.id);

        // 记录节点
        nodeEntity[d.id] = 'script';

        // 缩减描述行数
        d.description = this.T.limitLines(d.description, 10);

        // 示例代码
        let shortScriptId = d.id.split('__').slice(1).join('__');
        let sampleCodeImportFromSameScriptSet  = `import __${shortScriptId} as ${shortScriptId}`;
        let sampleCodeImportFromOtherScriptSet = `import ${d.id} as ${shortScriptId}`;

        // 创建节点数据
        let isCodeEdited   = d.codeMD5 !== d.codeDraftMD5;
        let lockedByUserId = d.sset_lockedByUserId || d.lockedByUserId;
        let lockedByUser   = d.sset_lockedByUserId
                            ? `${d.sset_lockedByUserName || d.sset_lockedByUsername || this.$t('UNKNOWN')}`
                            : `${d.lockedByUserName || d.lockedByUsername || this.$t('UNKNOWN')}`;
        let isLockedByMe        = lockedByUserId === this.$store.getters.userId;
        let isLockedByOther     = lockedByUserId && !isLockedByMe;
        let isLocked            = isLockedByMe || isLockedByOther;
        let isLockedByScriptSet = isLocked && !!d.sset_lockedByUserId;
        let isEditable          = this.$store.getters.isAdmin || !isLockedByOther;
        scriptMap[d.id] = {
          id                 : d.id,
          scriptSetId        : d.scriptSetId,
          label              : d.title || shortScriptId,
          type               : 'script',
          isCodeEdited       : isCodeEdited,
          lockedByUser       : lockedByUser,
          isLockedByMe       : isLockedByMe,
          isLockedByOther    : isLockedByOther,
          isLocked           : isLocked,
          isLockedByScriptSet: isLockedByScriptSet,
          isEditable         : isEditable,

          title      : d.title,
          description: d.description,

          sampleCodeImportFromSameScriptSet : sampleCodeImportFromSameScriptSet,
          sampleCodeImportFromOtherScriptSet: sampleCodeImportFromOtherScriptSet,

          children   : [],
          showPopover: false,
        };
        this.T.appendSearchFields(scriptMap[d.id], ['id', 'title'])

        // 插入上一层节点"children"
        if (scriptSetMap[d.scriptSetId]) {
          scriptSetMap[d.scriptSetId].children.push(scriptMap[d.id]);
        }
      });

      /***** 函数 *****/
      apiRes = await this.T.callAPI_getAll('/api/v1/funcs/do/list', {
        query: {
          fields: [
            'id',
            'title',
            'description',
            'definition',
            'scriptSetId',
            'scriptId',
            'sset_type',
            'integration',
            'extraConfigJSON',
          ]
        },
      });
      if (!apiRes || !apiRes.ok) return;

      window._DFF_funcIds = [];
      apiRes.data.forEach(d => {
        // 跳过不存在的函数
        if (!scriptMap[d.scriptId]) return;

        window._DFF_funcIds.push(d.id);

        // 记录节点
        nodeEntity[d.id] = 'func';

        // 缩减描述行数
        d.description = this.T.limitLines(d.description, 10);

        // 示例代码
        let shortScriptId = d.scriptId.split('__').slice(1).join('__');
        let sampleCodeImportFromSameScriptSet  = `import __${shortScriptId} as ${shortScriptId}\n${shortScriptId}.${d.definition}`;
        let sampleCodeImportFromOtherScriptSet = `import ${d.scriptId} as ${shortScriptId}\n${shortScriptId}.${d.definition}`;

        // 创建节点数据
        funcMap[d.id] = {
          id         : d.id,
          scriptSetId: d.scriptSetId,
          scriptId   : d.scriptId,
          label      : d.title || d.id,
          type       : 'func',
          definition : d.definition,

          title      : d.title,
          description: d.description,
          queue      : (d.extraConfigJSON || {}).queue,

          disabled: !this.$store.state.codeEditor_isCodeLoaded,

          sampleCodeImportFromSameScriptSet : sampleCodeImportFromSameScriptSet,
          sampleCodeImportFromOtherScriptSet: sampleCodeImportFromOtherScriptSet,

          showPopover: false,
        };
        this.T.appendSearchFields(funcMap[d.id], ['id', 'title'])

        // 插入上一层节点"children"
        if (scriptMap[d.scriptId]) {
          scriptMap[d.scriptId].children.push(funcMap[d.id]);
        }
      });

      // 转换为tree数据，并增加「刷新」/「添加脚本集/脚本」项
      let treeData = Object.values(scriptSetMap);
      treeData.forEach(d => {
        d.children.sort(this.T.asideItemSorter);
      })
      treeData.sort(this.T.scriptSetSorter);
      treeData.unshift({ type: 'addScriptSet' });
      treeData.unshift({ type: 'refresh' });

      // 隐藏脚本提示项
      if (hasHiddenScripts) {
        let scriptHiddenTip = this.$t("In most cases, the Script Sets that users doesn't need to care about are hidden by default.");
        if (this.$store.getters.isAdmin) {
          scriptHiddenTip += '<br>' + this.$t("You can change the default behavior in [Management / System Settings].");
        }

        treeData.push({
          type    : 'scriptSetHiddenTip',
          tipTitle: this.$t('Some Script Sets have been hidden'),
          tip     : scriptHiddenTip,
        });
      }

      // 清理无效数据（已经不存在的节点）
      let _d = this.T.jsonCopy(this.$store.state.asideScript_expandedNodeMap);
      for (let nodeId in _d) {
        if (!nodeEntity[nodeId]) delete _d[nodeId];
      }
      this.$store.commit('updateAsideScript_expandedNodeMap', _d);

      // 清理无效数据（代码编辑器中，已经不存在的脚本/无高亮行的脚本）
      _d = this.T.jsonCopy(this.$store.state.codeEditor_highlightedLineConfigMap);
      for (let scriptId in _d) {
        if (!scriptMap[scriptId] || this.T.isNothing(_d[scriptId])) delete _d[scriptId];
      }
      this.$store.commit('updateCodeEditor_highlightedLineConfigMap', _d);

      // 清理无效数据（代码查看器中，已经不存在的脚本/无高亮行的脚本）
      _d = this.T.jsonCopy(this.$store.state.codeViewer_highlightedLineConfigMap);
      for (let scriptId in _d) {
        if (!scriptMap[scriptId] || this.T.isNothing(_d[scriptId])) delete _d[scriptId];
      }
      this.$store.commit('updateCodeViewer_highlightedLineConfigMap', _d);

      // 生成选择器选项
      let selectOptions = [];
      [scriptSetMap, scriptMap, funcMap].forEach(x => {
        let _options = Object.values(x);
        _options.sort(this.T.asideItemSorter);
        selectOptions = selectOptions.concat(_options)
      });

      // 加载数据
      this.loading           = false;
      this.data              = treeData;
      this.selectOptions     = selectOptions;
      this.selectShowOptions = selectOptions;

      this.scriptSetMap = scriptSetMap;
      this.scriptMap    = scriptMap;
      this.funcMap      = funcMap;

      // 自动展开
      this.expandedNodeMap = this.$store.state.asideScript_expandedNodeMap || {};
      this.defaultExpandedNodeKeys = Object.keys(this.expandedNodeMap);

      // 自动选择
      this.selectNode(this.$route.params.id);
    },
    async pinData(dataType, dataId, isPinned) {
      let apiPath   = null;
      let okMessage = null;
      switch(dataType) {
        case 'scriptSet':
          apiPath   = '/api/v1/script-sets/:id/do/modify';
          okMessage = isPinned
                    ? this.$t('Script Set pinned')
                    : this.$t('Script Set unpinned');
          break;

        default:
          return;
      }
      let apiRes = await this.T.callAPI('post', apiPath, {
        params: { id: dataId },
        body  : { data: { isPinned: isPinned } },
        alert : { okMessage: okMessage },
      });
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateScriptListSyncTime');
    },
    async lockData(dataType, dataId, isLocked) {
      let apiPath   = null;
      let okMessage = null;
      switch(dataType) {
        case 'scriptSet':
          apiPath   = '/api/v1/script-sets/:id/do/modify';
          okMessage = isLocked
                    ? this.$t('Script Set locked')
                    : this.$t('Script Set unlocked');
          break;

        case 'script':
          apiPath   = '/api/v1/scripts/:id/do/modify';
          okMessage = isLocked
                    ? this.$t('Script locked')
                    : this.$t('Script unlocked');
          break;
      }
      let apiRes = await this.T.callAPI('post', apiPath, {
        params: { id: dataId },
        body  : { data: { isLocked: isLocked } },
        alert : { okMessage: okMessage },
      });
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateScriptListSyncTime');
    },
    async cloneData(data) {
      data.showPopover = false;

      let promptOpt = {
        inputValidator: v => {
          if (v.length <= 0) {
            return this.$t('Please input ID');
          } else if (v.length > 32) {
            return this.$t('Script Set ID too long');
          } else if (!v.match(/^[a-zA-Z0-9_]*$/g)) {
            return this.$t('Only alphabets, numbers and underscore are allowed');
          } else if (!v.match(/^[^0-9]/g)) {
            return this.$t('Cannot not starts with a number');
          }
          return true;
        }
      }
      let newScriptSetId = await this.T.prompt(this.$t('Please input new Script Set ID'), `${data.id}_2`, promptOpt);
      if (!newScriptSetId) return;

      // 检查重名
      let apiRes = await this.T.callAPI_getOne('/api/v1/script-sets/do/list', newScriptSetId);
      if (apiRes.data) {
        return this.T.alert(this.$t('Inputed Script Set ID already exists'));
      }

      // 执行克隆
      apiRes = await this.T.callAPI('post', '/api/v1/script-sets/:id/do/clone', {
        params: { id: data.id },
        body  : { newId: newScriptSetId },
        alert : { okMessage: this.$t('Script Set cloned') },
      });
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateScriptListSyncTime');
    },
    async exportData(data) {
      data.showPopover = false;

      let opt = {
        respType: 'blob',
        packResp: true,
        body    : { scriptSetIds: [ data.id ], note: this.$t('Export Script Set') },
      };

      let apiRes = await this.T.callAPI('post', '/api/v1/script-sets/do/export', opt);
      if (!apiRes || !apiRes.ok) return;

      let blob = new Blob([apiRes.data], {type: apiRes.extra.contentType});

      // 文件名为固定开头+时间
      let fileNameParts = [
        data.id,
        this.M().utcOffset('+08:00').format('YYYYMMDD_HHmmss'),
      ];
      let fileName = fileNameParts.join('-') + '.zip';
      FileSaver.saveAs(blob, fileName);

      await this.T.alert(this.$t('Script Set exported'), 'success');
    },
    showQuickViewWindow(data) {
      data.showPopover = false;

      this.$refs.quickViewWindow.showWindow(data.id);
    },

    openEntity(data, target) {
      data.showPopover = false;

      let setCodeLoading = (nextScriptId) => {
        if (this.$route.name === 'code-editor' && this.$route.params.id !== nextScriptId) {
          this.$store.commit('updateCodeEditor_isCodeLoaded', false);
        }
      }

      switch(data.type) {
        // 刷新
        case 'refresh':
          this.loadData();
          break;

        // 「添加脚本集」节点
        case 'addScriptSet':
          this.$refs.ScriptSetSetup.loadData();
          break;

        // 脚本集节点
        case 'scriptSet':
          if (target === 'add') {
            // 添加脚本
            this.selectNode(data.id, { expandChildren: true });
            this.$refs.ScriptSetup.loadData(data.id);

          } else if (target === 'setup') {
            // 打开脚本集配置
            this.selectNode(data.id, { expandChildren: false });
            this.$refs.ScriptSetSetup.loadData(data.id);

          } else if (target === 'scriptMarket') {
            // 前往脚本市场
            this.$router.push({
              name  : 'script-market-contents',
              params: {id: data.originId},
            });

          } else {
            // 点击脚本
            this.selectNode(data.id, { expandChildren: true });
          }
          break;

        // 脚本节点
        case 'script':
          if (target === 'add') {
            // 添加脚本
            this.selectNode(data.id, { expandChildren: true });
            this.$refs.ScriptSetup.loadData(data.scriptSetId);

          } else if (target === 'setup') {
            // 打开脚本配置
            this.selectNode(data.id, { expandChildren: false });
            this.$refs.ScriptSetup.loadData(data.id.split('__')[0], data.id);

          } else if ((this.$route.name === 'code-viewer' || this.$route.name === 'code-editor')
                && data.id === this.$route.params.id) {
            // 点击当前脚本
            this.selectNode(data.id, { expandChildren: true });

          } else {
            // 点击其他脚本
            this.selectNode(data.id, { expandChildren: true });

            setCodeLoading(data.id);

            this.$router.push({
              name  : 'code-viewer',
              params: { id: data.id },
            });

          }
          break;

        // 函数节点
        case 'func':
          // 高亮选中函数
          this.$store.commit('updateEditor_selectedItemId', data.id);

          if ((this.$route.name === 'code-viewer' || this.$route.name === 'code-editor')
                && data.scriptId === this.$route.params.id) {
            // 点击同一脚本内函数
            this.selectNode(data.id, { expandChildren: false });

          } else {
            // 点击不同脚本下的函数
            this.selectNode(data.id, { expandChildren: false });

            setCodeLoading(data.scriptId);
            this.$router.push({
              name  : 'code-viewer',
              params: { id: data.scriptId },
            });
          }

          break;

        default:
          console.error(`Unexcepted data type: ${data.type}`);
          break;
      }
    },
    async deleteEntity(data) {
      let apiPath     = null;
      let confirmText = null;
      let finishText  = null;
      switch(data.type) {
        // 脚本集节点
        case 'scriptSet':
          apiPath     = '/api/v1/script-sets/:id/do/delete';
          confirmText = this.$t('Are you sure you want to delete the Script Set?<br><strong class="text-bad">{label}</strong>', { label: data.label });
          finishText  = this.$t('Script Set deleted');
          break;

        // 脚本节点
        case 'script':
          apiPath     = '/api/v1/scripts/:id/do/delete';
          confirmText = this.$t('Are you sure you want to delete the Script?<br><strong class="text-bad">{label}</strong>', { label: data.label });
          finishText  = this.$t('Script deleted');
          break;

        default:
          return;
      }
      if (!await this.T.confirm(confirmText)) return;

      this.T.jumpDeletedEntity(data.id);

      let apiRes = await this.T.callAPI(apiPath, {
        params: { id: data.id },
        alert : { okMessage: finishText },
      });
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateScriptListSyncTime');

    },

    async loadRelEntityData(data) {
      let apiRes  = null;
      let listOpt = {
        query: {
          origin       : 'user',
          funcId       : data.id,
          pageSize     : 20,
        }
      };

      // 加载同步 API 列表
      apiRes = await this.T.callAPI_get('/api/v1/sync-apis/do/list', listOpt);
      if (apiRes.ok) {
        this.relEntities.syncAPIs = apiRes.data;
      }

      // 加载异步 API 列表
      apiRes = await this.T.callAPI_get('/api/v1/async-apis/do/list', listOpt);
      if (apiRes.ok) {
        this.relEntities.asyncAPIs = apiRes.data;
      }

      // 加载定时任务列表
      apiRes = await this.T.callAPI_get('/api/v1/cron-jobs/do/list', listOpt);
      if (apiRes.ok) {
        this.relEntities.cronJobs = apiRes.data;
      }
    },
    async openRelEntity(node, data, target) {
      data.showPopover = false;

      await this.loadRelEntityData(data);

      this.relEntityFunc   = data;
      this.relEntityTarget = target;
      this.showRelEntity   = true;
    },
    async showAPI(d, urlPattern) {
      // 获取函数详情
      let apiRes = await this.T.callAPI_getOne('/api/v1/funcs/do/list', d.funcId);
      if (!apiRes || !apiRes.ok) return;

      // 生成API请求示例
      let apiURL = this.T.formatURL(urlPattern, {
        baseURL: true,
        params : { id: d.id },
      });

      let funcCallKwargsJSON = {};
      for (let k in d.funcCallKwargsJSON) if (d.funcCallKwargsJSON.hasOwnProperty(k)) {
        if (this.common.isFuncArgumentPlaceholder(d.funcCallKwargsJSON[k])) {
          funcCallKwargsJSON[k] = d.funcCallKwargsJSON[k];
        }
      }
      let apiBody = { kwargs: funcCallKwargsJSON };
      let funcKwargs = apiRes.data.kwargsJSON;

      this.$refs.apiExampleDialog.update(apiURL, apiBody, funcKwargs);
    },
    async startCronJobManually(d) {
      if (!await this.T.confirm(this.$t('Are you sure you want to start the Cron Job manually?'))) return;

      let apiRes = await this.T.callAPI('post', '/api/v1/cron/:id', {
        params: { id: d.id },
        alert : { okMessage: this.$t('Cron Job Started Manually') },
      });
    },
  },
  computed: {
    highlightedFuncId() {
      switch(this.$route.name) {
        case 'code-editor':
        case 'code-viewer':
          return this.$store.state.Editor_selectedItemId;

        default:
          return null;
      }
    },
  },
  props: {
  },
  data() {
    return {
      loading: false,
      data   : [],

      selectFilterText : '',
      selectOptions    : [],
      selectShowOptions: [],

      scriptSetMap: {},
      scriptMap   : {},
      funcMap     : {},

      // 直接修改el-tree的`default-expanded-keys`参数会导致过渡动画被跳过
      // 因此需要将初始状态单独提取且防止中途修改
      expandedNodeMap        : {},
      defaultExpandedNodeKeys: [],

      showRelEntity    : false,
      showRelEntityData: false,
      relEntityTarget  : '',
      relEntityFunc    : {},
      relEntities: {
        syncAPIs : [],
        asyncAPIs: [],
        cronJobs : [],
      },
    };
  },
  created() {
    this.loadData();
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.goto-links {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding-top: 10px;
}
.goto-links > a {
  font-size: 14px;
  padding-top: 10px;
  display: inline-block;
}
.jump-to-select {
  position: absolute;
  left: 5px;
  right: 9px;
  z-index: 9;
}
.select-item-name {
  float: left;
}
.select-item-id {
  float: right;
  padding-left: 30px;
  font-size: 12px;
}

.aside-tree {
  padding-top: 35px;
}
.aside-tree-node {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 14px;
  padding-right: 8px;
  height: 31px;
  max-width: 100%;
  overflow: hidden;
}
.aside-tree-node i.fa {
  font-size: 14px;
}
.aside-tip pre {
  padding: 0 0 0 10px;
  margin: 0;
  font-size: 14px;
}
.aside-tree-node-description {

}
.aside-tree-node-sample {
  padding-top: 10px;
  text-align: left;
}
.aside-tree-node-quick-view {
  margin-left: 5px;
}
.aside-tree-node-tip {
  width: 400px;
  word-break: normal;
  line-height: 2;
}

.aside-tree-node > span {
  display: block;
  width: 100%;
}
.aside-item {
  height: 31px;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.code-edited-tip {
  font-size: 14px;
  padding-top: 5px;
  padding-bottom: 5px;
}
.child-nodes-count {
  font-size: 14px;
}

</style>
