<i18n locale="zh-CN" lang="yaml">
User Profile: 用户信息

You are signed in as a integrated user, please change your profile in the origin system: 当前登录用户为集成登录用户，修改信息请前往原系统进行操作

Please input name : 请输入名称
Please input email: 请输入邮箱

User Profile saved: 用户信息已保存
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Please input email: 請輸入郵箱
Please input name: 請輸入名稱
User Profile: 用户信息
User Profile saved: 用户信息已保存
You are signed in as a integrated user, please change your profile in the origin system: 當前登錄用户為集成登錄用户，修改信息請前往原系統進行操作
</i18n>
<i18n locale="zh-TW" lang="yaml">
Please input email: 請輸入郵箱
Please input name: 請輸入名稱
User Profile: 使用者資訊
User Profile saved: 使用者資訊已儲存
You are signed in as a integrated user, please change your profile in the origin system: 當前登入使用者為整合登入使用者，修改資訊請前往原系統進行操作
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <transition name="fade">
    <el-container direction="vertical" v-show="$store.state.isLoaded">
      <!-- 标题区 -->
      <el-header height="60px">
        <h1>
          {{ $t('User Profile')}}
        </h1>
      </el-header>

      <!-- 编辑区 -->
      <el-main>
        <el-row :gutter="20">
          <el-col :span="15">
            <div class="setup-form">
              <el-form ref="form" label-width="135px" :model="form" :rules="formRules" :disabled="$store.getters.isIntegratedUser">
                <el-form-item>
                  <InfoBlock v-if="$store.getters.isIntegratedUser" type="warning" :title="$t('You are signed in as a integrated user, please change your profile in the origin system')" />
                </el-form-item>

                <el-form-item :label="$t('Username')">
                  <el-input :disabled="true" v-model="data.username"></el-input>
                </el-form-item>

                <el-form-item :label="$t('Name')" prop="name">
                  <el-input
                    maxlength="200"
                    v-model="form.name"></el-input>
                </el-form-item>

                <el-form-item :label="$t('Email')" prop="email">
                  <el-input
                    maxlength="200"
                    v-model="form.email"></el-input>
                </el-form-item>

                <el-form-item :label="$t('Mobile')" prop="mobile">
                  <el-input
                    maxlength="30"
                    v-model="form.mobile"></el-input>
                </el-form-item>

                <el-form-item>
                  <el-button type="primary" @click="submitData">{{ $t('Modify') }}</el-button>
                </el-form-item>
              </el-form>
            </div>
          </el-col>
          <el-col :span="9" class="hidden-md-and-down">
          </el-col>
        </el-row>
      </el-main>
    </el-container>
  </transition>
</template>

<script>
export default {
  name: 'ProfileSetup',
  components: {
  },
  watch: {
    $route: {
      immediate: true,
      async handler(to, from) {
        await this.loadData();
      }
    },
    show(val) {
      if (val && this.$refs.form) {
        this.$refs.form.clearValidate();
      }
    },
  },
  methods: {
    async loadData() {
      let apiRes = await this.T.callAPI_get('/api/v1/auth/profile/do/get');
      if (!apiRes || !apiRes.ok) return;

      this.data = apiRes.data;

      let nextForm = {};
      Object.keys(this.form).forEach(f => nextForm[f] = this.data[f]);
      this.form = nextForm;

      this.$store.commit('updateLoadStatus', true);
    },
    async submitData() {
      try {
        await this.$refs.form.validate();
      } catch(err) {
        return console.error(err);
      }

      let apiRes = await this.T.callAPI('post', '/api/v1/auth/profile/do/modify', {
        body  : { data: this.T.jsonCopy(this.form) },
        alert : { okMessage: this.$t('User Profile saved') },
      });
      if (!apiRes || !apiRes.ok) return;

      await this.loadData();
      this.$store.dispatch('loadUserProfile');
    },
  },
  data() {
    return {
      data: {},
      form: {
        name  : null,
        email : null,
        mobile: null,
      },
      formRules: {
        name: [
          {
            trigger : 'change',
            message : this.$t('Please input name'),
            required: true,
          },
        ],
        email: [
          {
            trigger : 'change',
            message : this.$t('Please input email'),
            required: false,
            pattern: this.C.RE_PATTERN.email,
          },
        ],
      },
    }
  },
}
</script>

<style scoped>
</style>
