<i18n locale="en" lang="yaml">
randomIDString: auln-{Random ID}

parameterHint  : 'When the parameter value is specified as "INPUT_BY_CALLER", this parameter is allowed to be specified by the caller'
shortcutDays   : '{n} day | {n} days'
recentTaskCount: 'recent {n} task | recent {n} tasks'
</i18n>

<i18n locale="zh-CN" lang="yaml">
randomIDString: auln-{随机 ID}

Add Auth Link  : 添加授权链接
Setup Auth Link: 配置授权链接

Customize ID: 定制 ID
Execute     : 执行
Arguments   : 参数指定
Task Record : 任务记录
Keep        : 保留
Tags        : 标签
Add Tag     : 添加标签
Show in doc : 显示于文档
Expires     : 有效期
Limiting    : 限流
Note        : 备注

URL Preview: URL预览
ID will be a part of the calling URL: 此 ID 用于生成调用时的 URL
'JSON formated arguments (**kwargs)': 'JSON 格式的参数（**kwargs）'
The Func accepts extra arguments not listed above: 本函数允许传递额外的自定义函数参数

'ID must starts with "{prefix}"': 'ID 必须以"{prefix}"开头'
'Only numbers, alphabets, dot(.), underscore(_) and hyphen(-) are allowed': 只能输入数字、英文、点（.）、下划线（_）以及连字符（-）
Please select Func: 请选择执行函数
'Please input arguments, input "{}" when no argument': '请输入参数，无参数时填写 "{}"'
Date cannot earlier than 1970: 日期不能早于 1970 年
Date cannot later than 2099: 日期不能晚于 2099 年

Auth Link created: 授权链接已创建
Auth Link saved  : 授权链接已保存
Auth Link deleted: 授权链接已删除

Are you sure you want to delete the Auth Link?: 是否确认删除此授权链接？
Invalid argument format: 参数格式不正确

parameterHint  : '参数值指定为 "INPUT_BY_CALLER" 时，允许调用时指定本参数'
shortcutDays   : '{n} 天'
recentTaskCount: '{n} 个近期任务'
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Add Auth Link: 添加授權鏈接
Add Tag: 添加標籤
Are you sure you want to delete the Auth Link?: 是否確認刪除此授權鏈接？
Arguments: 參數指定
Auth Link created: 授權鏈接已創建
Auth Link deleted: 授權鏈接已刪除
Auth Link saved: 授權鏈接已保存
Customize ID: 定製 ID
Date cannot earlier than 1970: 日期不能早於 1970 年
Date cannot later than 2099: 日期不能晚於 2099 年
Execute: 執行
Expires: 有效期
ID must starts with "{prefix}": ID 必須以"{prefix}"開頭
ID will be a part of the calling URL: 此 ID 用於生成調用時的 URL
Invalid argument format: 參數格式不正確
JSON formated arguments (**kwargs): JSON 格式的參數（**kwargs）
Keep: 保留
Limiting: 限流
Note: 備註
Only numbers, alphabets, dot(.), underscore(_) and hyphen(-) are allowed: 只能輸入數字、英文、點（.）、下劃線（_）以及連字符（-）
Please input arguments, input "{}" when no argument: 請輸入參數，無參數時填寫 "{}"
Please select Func: 請選擇執行函數
Setup Auth Link: 配置授權鏈接
Show in doc: 顯示於文檔
Tags: 標籤
Task Record: 任務記錄
The Func accepts extra arguments not listed above: 本函數允許傳遞額外的自定義函數參數
URL Preview: URL預覽
parameterHint: 參數值指定為 "INPUT_BY_CALLER" 時，允許調用時指定本參數
randomIDString: auln-{隨機 ID}
recentTaskCount: '{n} 個近期任務'
shortcutDays: '{n} 天'
</i18n>
<i18n locale="zh-TW" lang="yaml">
Add Auth Link: 新增授權連結
Add Tag: 新增標籤
Are you sure you want to delete the Auth Link?: 是否確認刪除此授權連結？
Arguments: 引數指定
Auth Link created: 授權連結已建立
Auth Link deleted: 授權連結已刪除
Auth Link saved: 授權連結已儲存
Customize ID: 定製 ID
Date cannot earlier than 1970: 日期不能早於 1970 年
Date cannot later than 2099: 日期不能晚於 2099 年
Execute: 執行
Expires: 有效期
ID must starts with "{prefix}": ID 必須以"{prefix}"開頭
ID will be a part of the calling URL: 此 ID 用於生成呼叫時的 URL
Invalid argument format: 引數格式不正確
JSON formated arguments (**kwargs): JSON 格式的引數（**kwargs）
Keep: 保留
Limiting: 限流
Note: 備註
Only numbers, alphabets, dot(.), underscore(_) and hyphen(-) are allowed: 只能輸入數字、英文、點（.）、下劃線（_）以及連字元（-）
Please input arguments, input "{}" when no argument: 請輸入引數，無引數時填寫 "{}"
Please select Func: 請選擇執行函式
Setup Auth Link: 配置授權連結
Show in doc: 顯示於文件
Tags: 標籤
Task Record: 任務記錄
The Func accepts extra arguments not listed above: 本函式允許傳遞額外的自定義函式引數
URL Preview: URL預覽
parameterHint: 引數值指定為 "INPUT_BY_CALLER" 時，允許呼叫時指定本引數
randomIDString: auln-{隨機 ID}
recentTaskCount: '{n} 個近期任務'
shortcutDays: '{n} 天'
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <el-dialog
    id="ScriptSetSetup"
    :visible.sync="show"
    :close-on-click-modal="false"
    :close-on-press-escape="false"
    width="750px">

    <template slot="title">
      {{ pageTitle }} <code class="text-main">{{ data.func_title }}</code>
    </template>

    <el-container direction="vertical">
      <el-main>
        <div class="setup-form">
          <el-form ref="form" label-width="135px" :model="form" :rules="formRules">
            <el-form-item :label="$t('Customize ID')" prop="useCustomId" v-if="pageMode === 'add'">
              <el-switch v-model="useCustomId"></el-switch>
              <span class="text-main float-right">
                {{ $t('URL Preview') }}{{ $t(':') }}
                <code class="code-font">{{ `/api/v1/al/${useCustomId ? form.id : $t('randomIDString')}` }}</code>
              </span>
            </el-form-item>

            <el-form-item label="ID" prop="id" v-show="useCustomId" v-if="pageMode === 'add'">
              <el-input
                maxlength="60"
                v-model="form.id">
              </el-input>
              <InfoBlock :title="$t('ID will be a part of the calling URL')" />
            </el-form-item>

            <el-form-item :label="$t('Execute')" prop="funcId">
              <el-cascader ref="funcCascader"
                popper-class="code-font"
                placeholder="--"
                filterable
                :filter-method="common.funcCascaderFilter"
                v-model="form.funcId"
                :options="funcCascader"
                :props="{ expandTrigger: 'hover', emitPath: false, multiple: false }"
                @change="autoFillFuncCallKwargsJSON">
                </el-cascader>
            </el-form-item>

            <el-form-item :label="$t('Arguments')" prop="funcCallKwargsJSON">
              <el-input
                type="textarea"
                v-model="form.funcCallKwargsJSON"
                resize="none"
                :autosize="{ minRows: 2 }"></el-input>
              <InfoBlock :title="$t('JSON formated arguments (**kwargs)')" />
              <InfoBlock :title="$t('parameterHint')" />

              <InfoBlock v-if="apiCustomKwargsSupport" type="success" :title="$t('The Func accepts extra arguments not listed above')" />
            </el-form-item>

            <el-form-item :label="$t('Tags')" prop="tagsJSON">
              <el-tag v-for="t in form.tagsJSON" :key="t" type="warning" size="small" closable @close="removeTag(t)">{{ t }}</el-tag>
              <el-input v-if="showAddTag" ref="newTag"
                v-model="newTag"
                size="mini"
                @keyup.enter.native="addTag"
                @blur="addTag"></el-input>
              <el-button v-else
                type="text"
                @click="openAddTagInput">{{ $t('Add Tag') }}</el-button>
            </el-form-item>

            <el-form-item :label="$t('Task Record')">
              <span class="task-record-limit-prefix">{{ $t('Keep') }} </span>
              <el-input-number class="task-record-limit-input"
                :min="$store.getters.SYSTEM_INFO('_TASK_RECORD_LIMIT_MIN')"
                :max="$store.getters.SYSTEM_INFO('_TASK_RECORD_LIMIT_MAX')"
                :step="10"
                :precision="0"
                v-model="form.taskRecordLimit"></el-input-number>
              <span class="task-record-limit-unit">{{ $tc('recentTaskCount', form.taskRecordLimit, { n: '' }) }} </span>
              <el-link class="right-button" type="primary" @click.stop="form.taskRecordLimit = $store.getters.SYSTEM_INFO('_TASK_RECORD_FUNC_LIMIT_BY_ORIGIN_AUTH_LINK')">{{ $t('Restore Default') }}</el-link>
            </el-form-item>

            <el-form-item :label="$t('API Auth')" prop="apiAuthId">
              <el-select v-model="form.apiAuthId">
                <el-option v-for="opt in apiAuthList" :label="opt.label" :key="opt.id" :value="opt.id"></el-option>
              </el-select>
            </el-form-item>

            <el-form-item :label="$t('Show in doc')" prop="showInDoc">
              <el-switch
                v-model="form.showInDoc">
              </el-switch>
            </el-form-item>

            <el-form-item :label="$t('Expires')" prop="expireTime">
              <el-date-picker
                v-model="form.expireTime"
                type="datetime"
                align="left"
                format="yyyy-MM-dd HH:mm:ss"
                default-time="23:59:59"
                :clearable="true"
                :picker-options="datetimePickerOptions">
              </el-date-picker>
            </el-form-item>

            <template v-for="(opt, index) in C.AUTH_LINK_THROTTLING">
              <el-form-item :label="index === 0 ? $t('Limiting') : ''" :prop="`throttlingJSON.${opt.key}`">
                <el-input-number class="throttling-input"
                  :min="1"
                  :step="1"
                  :precision="0"
                  v-model="form.throttlingJSON[opt.key]"></el-input-number>
                <span class="throttling-unit">{{ $tc(opt.name, form.throttlingJSON[opt.key], { n: '' }) }} </span>
                <el-link class="right-button" @click.stop="form.throttlingJSON[opt.key] = undefined">{{ $t('Clear') }}</el-link>
              </el-form-item>
            </template>

            <el-form-item :label="$t('Note')">
              <el-input :placeholder="$t('Optional')"
                type="textarea"
                resize="none"
                :autosize="{minRows: 2}"
                maxlength="5000"
                v-model="form.note"></el-input>
            </el-form-item>

            <el-form-item class="setup-footer">
              <el-button class="danger-button float-left" v-if="pageMode === 'setup'" @click="deleteData">{{ $t('Delete') }}</el-button>
              <el-button type="primary" v-prevent-re-click @click="submitData">{{ $t('Save') }}</el-button>
            </el-form-item>
          </el-form>
        </div>
      </el-main>
    </el-container>
  </el-dialog>
</template>

<script>
export default {
  name: 'AuthLinkSetup',
  components: {
  },
  watch: {
    show(val) {
      if (val && this.$refs.form) {
        this.$refs.form.clearValidate();
      }

      if (!val) {
        this.$root.$emit('reload.authLinkList');
      }
    },
    'form.id'(val) {
      if (val && (val.length < this.ID_PREFIX.length || val.indexOf(this.ID_PREFIX) < 0)) {
        this.form.id = this.ID_PREFIX;
      }
    },
    useCustomId(val) {
      if (val) {
        this.form.id = `${this.ID_PREFIX}my-auth-link`;
      } else {
        this.form.id = null;
      }
    },
  },
  methods: {
    async loadData(id) {
      if (!id) {
        this.pageMode = 'add';
        this.T.jsonClear(this.form);
        this.form.throttlingJSON  = {};
        this.form.showInDoc       = false;
        this.form.taskRecordLimit = this.$store.getters.SYSTEM_INFO('_TASK_RECORD_FUNC_LIMIT_BY_ORIGIN_AUTH_LINK');
        this.data = {};

      } else {
        this.pageMode = 'setup';
        this.data.id = id;

        let apiRes = await this.T.callAPI_getOne('/api/v1/auth-links/do/list', this.data.id);
        if (!apiRes || !apiRes.ok) return;

        this.data = apiRes.data;

        let nextForm = {};
        Object.keys(this.form).forEach(f => nextForm[f] = this.data[f]);
        nextForm.funcCallKwargsJSON = JSON.stringify(nextForm.funcCallKwargsJSON, null, 2);
        nextForm.tagsJSON           = nextForm.tagsJSON || [];
        nextForm.apiAuthId          = this.data.apia_id;
        nextForm.throttlingJSON     = nextForm.throttlingJSON || {};

        this.form = nextForm;
      }

      // 获取函数列表
      let funcList = await this.common.getFuncList();

      this.funcMap      = funcList.map;
      this.funcCascader = funcList.cascader;

      // 获取API认证列表
      let apiAuthList = await this.common.getAPIAuthList();

      this.apiAuthList = apiAuthList;

      this.show = true;
    },
    async submitData() {
      try {
        await this.$refs.form.validate();
      } catch(err) {
        return console.error(err);
      }

      switch(this.pageMode) {
        case 'add':
          return await this.addData();
        case 'setup':
          return await this.modifyData();
      }
    },
    async addData() {
      let opt = {
        body : { data: this.T.jsonCopy(this.form) },
        alert: { okMessage: this.$t('Auth Link created') },
      };

      // 添加函数调用参数kwargsJSON
      try {
        opt.body.data.funcCallKwargsJSON = JSON.parse(this.form.funcCallKwargsJSON);
      } catch(err) {
        return this.T.alert(`${this.$t('Invalid argument format')}<br>${err.toString()}`);
      }

      let apiRes = await this.T.callAPI('post', '/api/v1/auth-links/do/add', opt);
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateHighlightedTableDataId', apiRes.data.id);
      this.show = false;
    },
    async modifyData() {
      let _formData = this.T.jsonCopy(this.form);
      delete _formData.id;

      let opt = {
        params: { id: this.data.id },
        body  : { data: _formData },
        alert : { okMessage: this.$t('Auth Link saved') },
      };

      // 添加函数调用参数kwargsJSON
      try {
        opt.body.data.funcCallKwargsJSON = JSON.parse(this.form.funcCallKwargsJSON);

      } catch(err) {
        return this.T.alert(`${this.$t('Invalid argument format')}<br>${err.toString()}`);
      }

      let apiRes = await this.T.callAPI('post', '/api/v1/auth-links/:id/do/modify', opt);
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateHighlightedTableDataId', apiRes.data.id);
      this.show = false;
    },
    async deleteData() {
      if (!await this.T.confirm(this.$t('Are you sure you want to delete the Auth Link?'))) return;

      let apiRes = await this.T.callAPI('/api/v1/auth-links/:id/do/delete', {
        params: { id: this.data.id },
        alert : { okMessage: this.$t('Auth Link deleted') },
      });
      if (!apiRes || !apiRes.ok) return;

      this.show = false;
    },
    autoFillFuncCallKwargsJSON(funcId) {
      // 自动填充调用参数
      let parameters = this.funcMap[funcId].argsJSON
                    || Object.keys(this.funcMap[funcId].kwargsJSON);

      let example = {};
      parameters.forEach(p => {
        if (p.indexOf('**') === 0) {
          // 暂定：不展示**kwargs参数
        } else {
          example[p] = 'INPUT_BY_CALLER';
        }
      });

      this.form.funcCallKwargsJSON = JSON.stringify(example, null, 2);
    },
    removeTag(tag) {
      this.form.tagsJSON.splice(this.form.tagsJSON.indexOf(tag), 1);
    },
    openAddTagInput() {
      this.showAddTag = true;
      this.$nextTick(_ => {
        this.$refs.newTag.$refs.input.focus();
      });
    },
    addTag() {
      let newTag = this.newTag;
      if (newTag) {
        if (!Array.isArray(this.form.tagsJSON)) {
          this.$set(this.form, 'tagsJSON', []);
        }
        this.form.tagsJSON.push(newTag);
      }
      this.showAddTag = false;
      this.newTag     = '';
    },
  },
  computed: {
    ID_PREFIX() {
      return 'auln-';
    },
    pageTitle() {
      const _map = {
        setup: this.$t('Setup Auth Link'),
        add  : this.$t('Add Auth Link'),
      };
      return _map[this.pageMode];
    },
    apiCustomKwargsSupport() {
      let funcId = this.form.funcId;
      if (!funcId) return false;
      if (!this.funcMap[funcId]) return false;

      for (let k in this.funcMap[funcId].kwargsJSON) {
        if (k.indexOf('**') === 0) return true;
      }
      return false;
    },
    datetimePickerOptions() {
      const now = new Date().getTime();
      const shortcutDaysList = [1, 3, 7, 30, 90, 365];
      let shortcuts = [];
      shortcutDaysList.forEach((days) => {
        let date = this.M().add(days, 'days').hours(23).minutes(59).seconds(59).toDate();

        shortcuts.push({
          text: this.$tc('shortcutDays', days),
          onClick(picker) {
            picker.$emit('pick', date);
          }
        });
      });

      return {
        shortcuts: shortcuts
      }
    },
  },
  props: {
  },
  data() {
    let errorMessage_funcCallKwargsJSON = this.$t('Please input arguments, input "{}" when no argument');

    return {
      show    : false,
      pageMode: null,

      data        : {},
      funcMap     : {},
      funcCascader: [],
      apiAuthList : [],

      useCustomId: false,
      showAddTag : false,
      newTag     : '',

      form: {
        id                : null,
        funcId            : null,
        funcCallKwargsJSON: null,
        tagsJSON          : [],
        apiAuthId         : null,
        expireTime        : null,
        throttlingJSON    : {},
        showInDoc         : false,
        taskRecordLimit   : this.$store.getters.SYSTEM_INFO('_TASK_RECORD_FUNC_LIMIT_BY_ORIGIN_AUTH_LINK'),
        note              : null,
      },

      formRules: {
        id: [
          {
            trigger: 'change',
            validator: (rule, value, callback) => {
              if (this.T.notNothing(value)) {
                if ((value.indexOf(this.ID_PREFIX) !== 0 || value === this.ID_PREFIX)) {
                  return callback(new Error(this.$t('ID must starts with "{prefix}"', { prefix: this.ID_PREFIX })));
                }
                if (!value.match(/^[0-9a-zA-Z\.\-\_]+$/g)) {
                  return callback(new Error(this.$t('Only numbers, alphabets, dot(.), underscore(_) and hyphen(-) are allowed')));
                }
              }
              return callback();
            },
          }
        ],
        funcId: [
          {
            trigger : 'change',
            message : this.$t('Please select Func'),
            required: true,
          },
        ],
        expireTime: [
          {
            trigger: 'change',
            validator: (rule, value, callback) => {
              let ts = this.M(value).unix();
              if (ts < this.T.MIN_UNIX_TIMESTAMP) {
                return callback(new Error(this.$t('Date cannot earlier than 1970')));
              } else if (ts > this.T.MAX_UNIX_TIMESTAMP) {
                return callback(new Error(this.$t('Date cannot later than 2099')));
              }
              return callback();
            },
          }
        ],
        funcCallKwargsJSON: [
          {
            trigger : 'change',
            message : errorMessage_funcCallKwargsJSON,
            required: true,
          },
          {
            trigger  : 'change',
            validator: (rule, value, callback) => {
              try {
                let j = JSON.parse(value);
                if (Array.isArray(j)) {
                  return callback(new Error(errorMessage_funcCallKwargsJSON));
                }
                return callback();

              } catch(err) {
                return callback(new Error(errorMessage_funcCallKwargsJSON));
              }
            },
          }
        ],
      },
    }
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.task-record-limit-input {
  width: 180px;
}
.task-record-limit-prefix {
  color: grey;
  padding-right: 10px;
}
.task-record-limit-unit {
  color: grey;
  padding-left: 10px;
}
.task-record-limit-unit > span {
  width: 35px;
  display: inline-block;
}
.throttling-input {
  width: 260px;
}
.throttling-unit {
  color: grey;
  padding-left: 10px;
}
.throttling-unit > span {
  width: 35px;
  display: inline-block;
}
</style>
