<i18n locale="en" lang="yaml">
lastSucceeded : 'Succeeded {t}'
lastFailed    : 'Failed {t}'
successCount  : 'Success {n}'
failureCount  : 'Failure {n}'
</i18n>

<i18n locale="zh-CN" lang="yaml">
Crontab Configs can temporarily pause globally              : 自动触发配置可以临时全局暂停
Crontab Configs has been paused globally, will resume in {0}: 自动触发配置已全局暂停，将在 {0} 后继续
Crontab Configs has been paused globally                    : 自动触发配置已全局暂停

Resume all          : 全部继续
Pause all           : 全部暂停
Pause for 15 minutes: 暂停 15 分钟
Pause for 30 minutes: 暂停 30 分钟
Pause for 1 hour    : 暂停 1 小时
Pause for 3 hours   : 暂停 3 小时
Pause for 12 hours  : 暂停 12 小时
Pause for 1 day     : 暂停 1 天

Fixed      : 固定
Not Set    : 未配置
Config     : 配置
Created    : 创建
Expires    : 过期
Task Record: 任务记录
Run        : 执行

Crontab Config disabled : 自动触发配置已禁用
Crontab Config enabled  : 自动触发配置已启用
Crontab Config deleted  : 自动触发配置已删除
Crontab Config Task sent: 自动触发配置任务已发送

Show all contents: 展示全部内容
No Crontab Config has ever been added: 从未添加过任何自动触发配置

Are you sure you want to disable the Crontab Config?: 是否确认禁用此自动触发配置？
Are you sure you want to delete the Crontab Config?: 是否确认删除此自动触发配置？
Are you sure you want to run the Crontab Config manually?: 是否确认手动执行此自动触发配置？

lastSucceeded : '{t}执行成功'
lastFailed    : '{t}执行失败'
successCount  : '成功 {n}'
failureCount  : '失败 {n}'

Using Crontab Config, you can have functions executed at regular intervals: 使用自动触发配置，可以让函数定时执行
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Are you sure you want to delete the Crontab Config?: 是否確認刪除此自動觸發配置？
Are you sure you want to disable the Crontab Config?: 是否確認禁用此自動觸發配置？
Are you sure you want to run the Crontab Config manually?: 是否確認手動執行此自動觸發配置？
Config: 配置
Created: 創建
Crontab Config Task sent: 自動觸發配置任務已發送
Crontab Config deleted: 自動觸發配置已刪除
Crontab Config disabled: 自動觸發配置已禁用
Crontab Config enabled: 自動觸發配置已啓用
Crontab Configs can temporarily pause globally: 自動觸發配置可以臨時全局暫停
Crontab Configs has been paused globally: 自動觸發配置已全局暫停
Crontab Configs has been paused globally, will resume in {0}: 自動觸發配置已全局暫停，將在 {0} 後繼續
Expires: 過期
Fixed: 固定
No Crontab Config has ever been added: 從未添加過任何自動觸發配置
Not Set: 未配置
Pause all: 全部暫停
Pause for 1 day: 暫停 1 天
Pause for 1 hour: 暫停 1 小時
Pause for 12 hours: 暫停 12 小時
Pause for 15 minutes: 暫停 15 分鐘
Pause for 3 hours: 暫停 3 小時
Pause for 30 minutes: 暫停 30 分鐘
Resume all: 全部繼續
Run: 執行
Show all contents: 展示全部內容
Task Record: 任務記錄
Using Crontab Config, you can have functions executed at regular intervals: 使用自動觸發配置，可以讓函數定時執行
failureCount: 失敗 {n}
lastFailed: '{t}執行失敗'
lastSucceeded: '{t}執行成功'
successCount: 成功 {n}
</i18n>
<i18n locale="zh-TW" lang="yaml">
Are you sure you want to delete the Crontab Config?: 是否確認刪除此自動觸發配置？
Are you sure you want to disable the Crontab Config?: 是否確認禁用此自動觸發配置？
Are you sure you want to run the Crontab Config manually?: 是否確認手動執行此自動觸發配置？
Config: 配置
Created: 建立
Crontab Config Task sent: 自動觸發配置任務已傳送
Crontab Config deleted: 自動觸發配置已刪除
Crontab Config disabled: 自動觸發配置已禁用
Crontab Config enabled: 自動觸發配置已啟用
Crontab Configs can temporarily pause globally: 自動觸發配置可以臨時全域性暫停
Crontab Configs has been paused globally: 自動觸發配置已全域性暫停
Crontab Configs has been paused globally, will resume in {0}: 自動觸發配置已全域性暫停，將在 {0} 後繼續
Expires: 過期
Fixed: 固定
No Crontab Config has ever been added: 從未新增過任何自動觸發配置
Not Set: 未配置
Pause all: 全部暫停
Pause for 1 day: 暫停 1 天
Pause for 1 hour: 暫停 1 小時
Pause for 12 hours: 暫停 12 小時
Pause for 15 minutes: 暫停 15 分鐘
Pause for 3 hours: 暫停 3 小時
Pause for 30 minutes: 暫停 30 分鐘
Resume all: 全部繼續
Run: 執行
Show all contents: 展示全部內容
Task Record: 任務記錄
Using Crontab Config, you can have functions executed at regular intervals: 使用自動觸發配置，可以讓函式定時執行
failureCount: 失敗 {n}
lastFailed: '{t}執行失敗'
lastSucceeded: '{t}執行成功'
successCount: 成功 {n}
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <transition name="fade">
    <el-container direction="vertical" v-show="$store.state.isLoaded">
      <!-- 标题区 -->
      <el-header height="60px">
        <div class="common-page-header">
          <h1>{{ $t('Crontab Config') }}</h1>
          <div class="header-control">
            <template v-if="T.notNothing(pauseTimeout)">
              <small>
                <i18n v-if="pauseTimeout > 0" path="Crontab Configs has been paused globally, will resume in {0}">
                  <el-tooltip effect="dark" :content="$tc('nSeconds', pauseTimeout)" placement="bottom">
                    <span class="text-bad">{{ T.duration(pauseTimeout * 1000, true) }}</span>
                  </el-tooltip>
                </i18n>
                <span v-else-if="pauseTimeout === -1" class="text-bad">{{ $t('Crontab Configs has been paused globally') }}</span>
              </small>

              <el-button v-if="pauseTimeout"
                size="small"
                class="success-button"
                @click="resumeAll()">
                <i class="fa fa-fw fa-play"></i>
                {{ $t('Resume all') }}
              </el-button>
              <el-tooltip v-else effect="dark" :content="$t('Crontab Configs can temporarily pause globally')" placement="left">
                <el-dropdown
                  split-button
                  size="small"
                  @click="pauseAll()"
                  @command="pauseAll">
                  <i class="fa fa-fw fa-pause"></i>
                  {{ $t('Pause all') }}

                  <el-dropdown-menu slot="dropdown">
                    <el-dropdown-item :command="15 * 60">{{ $t('Pause for 15 minutes') }}</el-dropdown-item>
                    <el-dropdown-item :command="30 * 60">{{ $t('Pause for 30 minutes') }}</el-dropdown-item>
                    <el-dropdown-item :command="60 * 60">{{ $t('Pause for 1 hour') }}</el-dropdown-item>
                    <el-dropdown-item :command="3 * 60 * 60">{{ $t('Pause for 3 hours') }}</el-dropdown-item>
                    <el-dropdown-item :command="12 * 60 * 60">{{ $t('Pause for 12 hours') }}</el-dropdown-item>
                    <el-dropdown-item :command="24 * 60 * 60">{{ $t('Pause for 1 day') }}</el-dropdown-item>
                  </el-dropdown-menu>
                </el-dropdown>
              </el-tooltip>
            </template>

            <FuzzySearchInput :dataFilter="dataFilter"></FuzzySearchInput>

            <el-tooltip :content="$t('Show all contents')" placement="bottom" :enterable="false">
              <el-checkbox
                :border="true"
                size="small"
                v-model="dataFilter.origin"
                true-label="_ALL"
                false-label="user"
                @change="T.changePageFilter(dataFilter)">{{ $t('Show all') }}</el-checkbox>
            </el-tooltip>
            <el-button @click="openSetup(null, 'add')" type="primary" size="small">
              <i class="fa fa-fw fa-plus"></i>
              {{ $t('New') }}
            </el-button>
          </div>
        </div>
      </el-header>

      <!-- 列表区 -->
      <el-main class="common-table-container">
        <div class="no-data-area" v-if="T.isNothing(data)">
          <h1 class="no-data-title" v-if="T.isPageFiltered({ ignore: { origin: '_ALL' } })"><i class="fa fa-fw fa-search"></i>{{ $t('No matched data found') }}</h1>
          <h1 class="no-data-title" v-else><i class="fa fa-fw fa-info-circle"></i>{{ $t('No Crontab Config has ever been added') }}</h1>

          <p class="no-data-tip">
            {{ $t('Using Crontab Config, you can have functions executed at regular intervals') }}
          </p>
        </div>
        <el-table v-else
          class="common-table" height="100%"
          :data="data"
          :row-class-name="T.getHighlightRowCSS">

          <el-table-column :label="$t('Func')" min-width="420">
            <template slot-scope="scope">
              <FuncInfo
                :config-func-id="scope.row.funcId"
                :id="scope.row.func_id"
                :title="scope.row.func_title"
                :kwargsJSON="scope.row.funcCallKwargsJSON" />

              <div>
                <span class="text-info">ID</span>
                &nbsp;<code class="text-main">{{ scope.row.id }}</code>
                <CopyButton :content="scope.row.id" />

                <template v-if="T.notNothing(scope.row.tagsJSON) || T.notNothing(scope.row.func_tagsJSON)">
                  <br>
                  <span class="text-info">&#12288;{{ $t('Tags') }}</span>
                  <el-tag size="mini" type="info" v-for="t in scope.row.func_tagsJSON" :key="t">{{ t }}</el-tag>
                  <el-tag size="mini" type="warning" v-for="t in scope.row.tagsJSON" :key="t">{{ t }}</el-tag>
                </template>

                <template v-if="scope.row.note">
                  <br>
                  <span class="text-info">&#12288;{{ $t('Note') }}{{ $t(':') }}</span>
                  <span>{{ scope.row.note }}</span>
                </template>
              </div>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Config')" width="240">
            <template slot-scope="scope">
              <span class="text-info">Crontab{{ $t(':') }}</span>
              <template v-if="scope.row.func_extraConfigJSON && scope.row.func_extraConfigJSON.fixedCrontab">
                <code class="text-main">{{ scope.row.func_extraConfigJSON.fixedCrontab }}</code>
                <el-tag size="mini">{{ $t('Fixed') }}</el-tag>
              </template>
              <code v-else-if="scope.row.crontab" class="text-main">{{ scope.row.crontab }}</code>
              <span v-else class="text-bad">{{ $t('Not Set') }}</span>

              <br>
              <span class="text-info">{{ $t('Created') }}{{ $t(':') }}</span>
              <RelativeDateTime :datetime="scope.row.createTime" />

              <br>
              <span class="text-info">{{ $t('Expires') }}{{ $t(':') }}</span>
              <span v-if="!scope.row.expireTime">-</span>
              <template v-else>
                <RelativeDateTime :datetime="scope.row.expireTime"
                  :class="T.isExpired(scope.row.expireTime) ? 'text-bad' : 'text-good'" />
              </template>
            </template>
          </el-table-column>

          <el-table-column v-if="isLocalFuncTaskRecordEnabled" :label="$t('Task Record')" width="240">
            <template slot-scope="scope">
              <template v-if="!isStatisticLoaded">
                <i class="fa fa-fw fa-circle-o-notch fa-spin"></i>
                {{ $t('Loading') }}
              </template>
              <template v-else-if="statisticMap[scope.row.id]">
                <span v-if="statisticMap[scope.row.id].lastStatus === 'success'" class="text-good">
                  <i class="fa fa-fw fa-check"></i> {{ $t('lastSucceeded', { t: T.fromNow(statisticMap[scope.row.id].lastStartTime) }) }}
                </span>
                <span v-else class="text-bad">
                  <i class="fa fa-fw fa-times"></i> {{ $t('lastFailed', { t: T.fromNow(statisticMap[scope.row.id].lastStartTime) }) }}
                </span>

                <br>
                <i class="fa fa-fw fa-pie-chart text-info"></i>
                <span :class="{ 'text-good': !!statisticMap[scope.row.id].recentSuccessCount }">{{ $t('successCount', { n: T.numberLimit(statisticMap[scope.row.id].recentSuccessCount) }) }}</span>
                / <span :class="{ 'text-bad': !!statisticMap[scope.row.id].recentFailureCount }">{{ $t('failureCount', { n: T.numberLimit(statisticMap[scope.row.id].recentFailureCount) }) }}</span>
              </template>
              <template v-else>
                {{ $t('No recent record') }}
              </template>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Status')" width="100">
            <template slot-scope="scope">
              <span v-if="scope.row.isDisabled" class="text-bad"><i class="fa fa-fw fa-ban"></i> {{ $t('Disabled') }}</span>
              <span v-else class="text-good"><i class="fa fa-fw fa-check"></i> {{ $t('Enabled') }}</span>
            </template>
          </el-table-column>

          <el-table-column align="right" width="350">
            <template slot-scope="scope">
              <template v-if="statisticMap[scope.row.id]">
                <el-link @click="common.goToTaskRecord({ origin: 'crontab', originId: scope.row.id }, { hlDataId: scope.row.id })" :disabled="!statisticMap[scope.row.id].taskRecordCount">
                  {{ $t('Task Record') }} <code v-if="statisticMap[scope.row.id].taskRecordCount">({{ T.numberLimit(statisticMap[scope.row.id].taskRecordCount) }})</code>
                </el-link>
              </template>
              <el-link @click="runTask(scope.row)" :disabled="!scope.row.func_id">
                {{ $t('Run') }}
              </el-link>

              <el-link :disabled="T.isNothing(scope.row.func_id)" v-if="scope.row.isDisabled" v-prevent-re-click @click="quickSubmitData(scope.row, 'enable')">{{ $t('Enable') }}</el-link>
              <el-link :disabled="T.isNothing(scope.row.func_id)" v-if="!scope.row.isDisabled" @click="quickSubmitData(scope.row, 'disable')">{{ $t('Disable') }}</el-link>
              <el-link @click="openSetup(scope.row, 'setup')">{{ $t('Setup') }}</el-link>
              <el-link @click="quickSubmitData(scope.row, 'delete')">{{ $t('Delete') }}</el-link>
            </template>
          </el-table-column>
        </el-table>
      </el-main>

      <!-- 翻页区 -->
      <Pager :pageInfo="pageInfo" />
      <CrontabConfigSetup ref="setup" />
    </el-container>
  </transition>
</template>

<script>
import CrontabConfigSetup from '@/components/Management/CrontabConfigSetup'

export default {
  name: 'CrontabConfigList',
  components: {
    CrontabConfigSetup,
  },
  watch: {
    $route: {
      immediate: true,
      async handler(to, from) {
        await this.loadData();
      }
    },
    '$store.state.isLoaded': function(val) {
      if (!val) return;

      setImmediate(() => this.T.autoScrollTable());
    },
  },
  methods: {
    async loadData(options) {
      options = options || {};

      // 默认过滤条件
      let _listQuery = this.dataFilter = this.T.createListQuery();
      if (this.T.isNothing(this.$route.query)) {
        _listQuery.origin = 'user';
      }

      let apiRes = await this.T.callAPI_get('/api/v1/crontab-configs/do/list', {
        query: _listQuery,
      });
      if (!apiRes || !apiRes.ok) return;

      this.data = apiRes.data;
      this.pageInfo = apiRes.pageInfo;

      this.$store.commit('updateLoadStatus', true);

      // 获取暂停标记
      await this.updatePauseTimeout();

      // 获取统计信息
      if (this.isLocalFuncTaskRecordEnabled && !options.skipStatistic) {
        this.isStatisticLoaded = false;
        setTimeout(async () => {
          this.statisticMap = await this.common.loadStatistic('originId', this.data.map(d => d.id));
          this.isStatisticLoaded = true;
        }, 1000);
      }
    },
    async quickSubmitData(d, operation) {
      switch(operation) {
        case 'disable':
          if (!await this.T.confirm(this.$t('Are you sure you want to disable the Crontab Config?'))) return;
          break;

        case 'delete':
          if (!await this.T.confirm(this.$t('Are you sure you want to delete the Crontab Config?'))) return;
          break;
      }

      let apiRes = null;
      switch(operation) {
        case 'disable':
          apiRes = await this.T.callAPI('post', '/api/v1/crontab-configs/:id/do/modify', {
            params: { id: d.id },
            body  : { data: { isDisabled: true } },
            alert : { okMessage: this.$t('Crontab Config disabled') },
          });
          break;

        case 'enable':
          apiRes = await this.T.callAPI('post', '/api/v1/crontab-configs/:id/do/modify', {
            params: { id: d.id },
            body  : { data: { isDisabled: false } },
            alert : { okMessage: this.$t('Crontab Config enabled') },
          });
          break;

        case 'delete':
          apiRes = await this.T.callAPI('/api/v1/crontab-configs/:id/do/delete', {
            params: { id: d.id },
            alert : { okMessage: this.$t('Crontab Config deleted') },
          });
          break;
      }
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateHighlightedTableDataId', d.id);

      await this.loadData({ skipStatistic: true });
    },
    openSetup(d, target) {
      switch(target) {
        case 'add':
          this.$refs.setup.loadData();
          break;

        case 'setup':
          this.$store.commit('updateHighlightedTableDataId', d.id);
          this.$refs.setup.loadData(d.id);
          break;
      }
    },
    async runTask(d) {
      if (!await this.T.confirm(this.$t('Are you sure you want to run the Crontab Config manually?'))) return;

      let apiRes = await this.T.callAPI('post', '/api/v1/cron/:id', {
        params: { id: d.id },
        alert : { okMessage: this.$t('Crontab Config Task sent') },
      });

      this.$store.commit('updateHighlightedTableDataId', d.id);
    },
    async pauseAll(ttl) {
      ttl = ttl || -1;
      let apiRes = await this.T.callAPI('post', '/api/v1/temporary-flags/:id/do/set', {
        params: { id: 'pauseAllCrontabConfigs' },
        body  : { ttl: ttl },
      });
      if (!apiRes || !apiRes.ok) return;

      await this.updatePauseTimeout();
    },
    async resumeAll() {
      let apiRes = await this.T.callAPI_get('/api/v1/temporary-flags/:id/do/clear', {
        params: { id: 'pauseAllCrontabConfigs' },
      });
      if (!apiRes || !apiRes.ok) return;

      await this.updatePauseTimeout();
    },
    async updatePauseTimeout() {
      let apiRes = await this.T.callAPI_get('/api/v1/temporary-flags/do/get', {
        query: { id: 'pauseAllCrontabConfigs' },
      });
      if (!apiRes || !apiRes.ok) return;

      this.pauseTimeout = apiRes.data.pauseAllCrontabConfigs.ttl || 0;
    },
  },
  computed: {
    isLocalFuncTaskRecordEnabled() {
      return !!this.$store.getters.SYSTEM_SETTINGS('LOCAL_FUNC_TASK_RECORD_ENABLED');
    },
  },
  props: {
  },
  data() {
    let _pageInfo   = this.T.createPageInfo();
    let _dataFilter = this.T.createListQuery();

    return {
      data    : [],
      pageInfo: _pageInfo,

      statisticMap     : {},
      isStatisticLoaded: false,

      dataFilter: {
        _fuzzySearch: _dataFilter._fuzzySearch,
        origin      : _dataFilter.origin,
      },

      pauseTimeout: null,

      autoRefreshTimer: null,
    }
  },
  created() {
    this.$root.$on('reload.crontabConfigList', () => this.loadData({ skipStatistic: true }));

    this.autoRefreshTimer = setInterval(() => {
      this.updatePauseTimeout();
    }, 10 * 1000);
  },
  destroyed() {
    this.$root.$off('reload.crontabConfigList');

    if (this.autoRefreshTimer) clearInterval(this.autoRefreshTimer);
  },
}
</script>

<style scoped>
</style>

<style>
.api-url-with-query .el-link--inner {
  padding: 0 5px;
}
</style>
