<i18n locale="en" lang="yaml">
recentTaskCount: 'recent {n} task | recent {n} tasks'
shortcutDays  : '{n} day | {n} days'
</i18n>

<i18n locale="zh-CN" lang="yaml">
Add Crontab Config  : 添加自动触发配置
Setup Crontab Config: 配置自动触发配置

Customize ID: 定制 ID
Execute     : 执行
Arguments   : 参数指定
Task Record : 任务记录
Keep        : 保留
Tags        : 标签
Add Tag     : 添加标签
Weekdays    : 按周重复
Months      : 按月重复
Days        : 按天重复
Hours       : 按小时重复
Minutes     : 按分钟重复
Expires     : 有效期
Note        : 备注

'(Fixed Crontab)': （固定Crontab）
Every weekday    : 不限星期
SUN              : 周日
MON              : 周一
TUE              : 周二
WED              : 周三
THU              : 周四
FRI              : 周五
SAT              : 周六
Every month      : 每月
Every 3 months   : 每 3 个月
Every 6 months   : 每 6 个月
Every day        : 每天
Every hour       : 每小时
Every 2 hours    : 每 2 小时
Every 3 hours    : 每 3 小时
Every 6 hours    : 每 6 小时
Every 12 hours   : 每 12 小时
Every minute     : 每分钟
Every 5 minutes  : 每 5 分钟
Every 15 minutes : 每 15 分钟
Every 30 minutes : 每 30 分钟

'JSON formated arguments (**kwargs)': 'JSON格式的参数（**kwargs）'
The Func accepts extra arguments not listed above: 本函数允许传递额外的自定义函数参数

'ID must starts with "{prefix}"': 'ID 必须以"{prefix}"开头'
'Only numbers, alphabets, dot(.), underscore(_) and hyphen(-) are allowed': 只能输入数字、英文、点（.）、下划线（_）以及连字符（-）
Please select Func: 请选择执行函数
'Please input arguments, input "{}" when no argument': '请输入参数，无参数时填写 "{}"'
Only date-time between 1970 and 2037 are allowed: 只能选择1970年至2037年之间的日期
Date-time cannot earlier than 1970: 日期不能早于1970年
Date-time cannot later than 2037: 时间不能晚于2037年

Crontab Config created: 自动触发配置已创建
Crontab Config saved  : 自动触发配置已保存
Crontab Config deleted: 自动触发配置已删除

Are you sure you want to delete the Crontab Config?: 是否确认删除此自动触发配置？
Invalid argument format: 参数格式不正确

recentTaskCount: '{n} 个近期任务'
shortcutDays  : '{n} 天'
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
(Fixed Crontab): （固定Crontab）
Add Crontab Config: 添加自動觸發配置
Add Tag: 添加標籤
Are you sure you want to delete the Crontab Config?: 是否確認刪除此自動觸發配置？
Arguments: 參數指定
Crontab Config created: 自動觸發配置已創建
Crontab Config deleted: 自動觸發配置已刪除
Crontab Config saved: 自動觸發配置已保存
Customize ID: 定製 ID
Date-time cannot earlier than 1970: 日期不能早於1970年
Date-time cannot later than 2037: 時間不能晚於2037年
Days: 按天重複
Every 12 hours: 每 12 小時
Every 15 minutes: 每 15 分鐘
Every 2 hours: 每 2 小時
Every 3 hours: 每 3 小時
Every 3 months: 每 3 個月
Every 30 minutes: 每 30 分鐘
Every 5 minutes: 每 5 分鐘
Every 6 hours: 每 6 小時
Every 6 months: 每 6 個月
Every day: 每天
Every hour: 每小時
Every minute: 每分鐘
Every month: 每月
Every weekday: 不限星期
Execute: 執行
Expires: 有效期
FRI: 週五
Hours: 按小時重複
ID must starts with "{prefix}": ID 必須以"{prefix}"開頭
Invalid argument format: 參數格式不正確
JSON formated arguments (**kwargs): JSON格式的參數（**kwargs）
Keep: 保留
MON: 週一
Minutes: 按分鐘重複
Months: 按月重複
Note: 備註
Only date-time between 1970 and 2037 are allowed: 只能選擇1970年至2037年之間的日期
Only numbers, alphabets, dot(.), underscore(_) and hyphen(-) are allowed: 只能輸入數字、英文、點（.）、下劃線（_）以及連字符（-）
Please input arguments, input "{}" when no argument: 請輸入參數，無參數時填寫 "{}"
Please select Func: 請選擇執行函數
SAT: 週六
SUN: 週日
Setup Crontab Config: 配置自動觸發配置
THU: 週四
TUE: 週二
Tags: 標籤
Task Record: 任務記錄
The Func accepts extra arguments not listed above: 本函數允許傳遞額外的自定義函數參數
WED: 週三
Weekdays: 按周重複
recentTaskCount: '{n} 個近期任務'
shortcutDays: '{n} 天'
</i18n>
<i18n locale="zh-TW" lang="yaml">
(Fixed Crontab): （固定Crontab）
Add Crontab Config: 新增自動觸發配置
Add Tag: 新增標籤
Are you sure you want to delete the Crontab Config?: 是否確認刪除此自動觸發配置？
Arguments: 引數指定
Crontab Config created: 自動觸發配置已建立
Crontab Config deleted: 自動觸發配置已刪除
Crontab Config saved: 自動觸發配置已儲存
Customize ID: 定製 ID
Date-time cannot earlier than 1970: 日期不能早於1970年
Date-time cannot later than 2037: 時間不能晚於2037年
Days: 按天重複
Every 12 hours: 每 12 小時
Every 15 minutes: 每 15 分鐘
Every 2 hours: 每 2 小時
Every 3 hours: 每 3 小時
Every 3 months: 每 3 個月
Every 30 minutes: 每 30 分鐘
Every 5 minutes: 每 5 分鐘
Every 6 hours: 每 6 小時
Every 6 months: 每 6 個月
Every day: 每天
Every hour: 每小時
Every minute: 每分鐘
Every month: 每月
Every weekday: 不限星期
Execute: 執行
Expires: 有效期
FRI: 週五
Hours: 按小時重複
ID must starts with "{prefix}": ID 必須以"{prefix}"開頭
Invalid argument format: 引數格式不正確
JSON formated arguments (**kwargs): JSON格式的引數（**kwargs）
Keep: 保留
MON: 週一
Minutes: 按分鐘重複
Months: 按月重複
Note: 備註
Only date-time between 1970 and 2037 are allowed: 只能選擇1970年至2037年之間的日期
Only numbers, alphabets, dot(.), underscore(_) and hyphen(-) are allowed: 只能輸入數字、英文、點（.）、下劃線（_）以及連字元（-）
Please input arguments, input "{}" when no argument: 請輸入引數，無引數時填寫 "{}"
Please select Func: 請選擇執行函式
SAT: 週六
SUN: 週日
Setup Crontab Config: 配置自動觸發配置
THU: 週四
TUE: 週二
Tags: 標籤
Task Record: 任務記錄
The Func accepts extra arguments not listed above: 本函式允許傳遞額外的自定義函式引數
WED: 週三
Weekdays: 按周重複
recentTaskCount: '{n} 個近期任務'
shortcutDays: '{n} 天'
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <el-dialog
    id="ScriptSetSetup"
    :visible.sync="show"
    :close-on-click-modal="false"
    :close-on-press-escape="false"
    width="750px">

    <template slot="title">
      {{ pageTitle }} <code class="text-main">{{ data.func_title }}</code>
    </template>

    <el-container direction="vertical">
      <el-main>
        <div class="setup-form">
          <el-form ref="form" label-width="135px" :model="form" :rules="formRules">
            <el-form-item :label="$t('Customize ID')" prop="useCustomId" v-if="pageMode === 'add'">
              <el-switch v-model="useCustomId"></el-switch>
            </el-form-item>

            <el-form-item label="ID" prop="id" v-show="useCustomId" v-if="pageMode === 'add'">
              <el-input
                maxlength="60"
                v-model="form.id">
              </el-input>
            </el-form-item>

            <el-form-item :label="$t('Execute')" prop="funcId">
              <el-cascader ref="funcCascader"
                popper-class="code-font"
                placeholder="--"
                filterable
                :filter-method="common.funcCascaderFilter"
                v-model="form.funcId"
                :options="funcCascader"
                :props="{ expandTrigger: 'hover', emitPath: false, multiple: false }"
                @change="autoFillFuncCallKwargsJSON">
                </el-cascader>
            </el-form-item>

            <el-form-item :label="$t('Arguments')" prop="funcCallKwargsJSON">
              <el-input
                type="textarea"
                v-model="form.funcCallKwargsJSON"
                resize="none"
                :autosize="{ minRows: 2 }"></el-input>
              <InfoBlock :title="$t('JSON formated arguments (**kwargs)')" />

              <InfoBlock v-if="apiCustomKwargsSupport" type="success" :title="$t('The Func accepts extra arguments not listed above')" />
            </el-form-item>

            <el-form-item :label="$t('Tags')" prop="tagsJSON">
              <el-tag v-for="t in form.tagsJSON" :key="t" type="warning" size="small" closable @close="removeTag(t)">{{ t }}</el-tag>
              <el-input v-if="showAddTag" ref="newTag"
                v-model="newTag"
                size="mini"
                @keyup.enter.native="addTag"
                @blur="addTag"></el-input>
              <el-button v-else
                type="text"
                @click="openAddTagInput">{{ $t('Add Tag') }}</el-button>
            </el-form-item>

            <el-form-item :label="$t('Task Record')">
              <span class="task-record-limit-prefix">{{ $t('Keep') }} </span>
              <el-input-number class="task-record-limit-input"
                :min="$store.getters.SYSTEM_INFO('_TASK_RECORD_LIMIT_MIN')"
                :max="$store.getters.SYSTEM_INFO('_TASK_RECORD_LIMIT_MAX')"
                :step="10"
                :precision="0"
                v-model="form.taskRecordLimit"></el-input-number>
              <span class="task-record-limit-unit">{{ $tc('recentTaskCount', form.taskRecordLimit, { n: '' }) }} </span>
              <el-link class="task-record-limit-clear" type="primary" @click.stop="form.taskRecordLimit = $store.getters.SYSTEM_INFO('_TASK_RECORD_FUNC_LIMIT_BY_ORIGIN_CRONTAB_CONFIG')">{{ $t('Restore Default') }}</el-link>
            </el-form-item>

            <!-- Crontab配置 -->
            <template v-if="!fixedCrontabExpr">
              <el-form-item label="Crontab">
                <code class="crontab-expr-parts crontab-expr-parts-minutes">{{ formCrontabExprParts.minutes }}</code>
                <code class="crontab-expr-parts crontab-expr-parts-hours">{{ formCrontabExprParts.hours }}</code>
                <code class="crontab-expr-parts crontab-expr-parts-days">{{ formCrontabExprParts.days }}</code>
                <code class="crontab-expr-parts crontab-expr-parts-months">{{ formCrontabExprParts.months }}</code>
                <code class="crontab-expr-parts crontab-expr-parts-weeks">{{ formCrontabExprParts.weeks }}</code>
              </el-form-item>

              <el-form-item :label="$t('Minutes')">
                <el-checkbox-group v-model="formCrontab.minutes">
                  <template v-for="(item, index) in MINUTES">
                    <br v-if="item === 'sep'">
                    <el-checkbox v-else
                      border
                      class="crontab-item-checkbox"
                      :key="item.expr"
                      :label="item.expr"
                      @change="autoFixCrontab">{{ item.name }}</el-checkbox>
                  </template>
                </el-checkbox-group>
              </el-form-item>

              <el-form-item :label="$t('Hours')">
                <el-checkbox-group v-model="formCrontab.hours">
                  <template v-for="(item, index) in HOURS">
                    <br v-if="item === 'sep'">
                    <el-checkbox v-else
                      border
                      class="crontab-item-checkbox"
                      :key="item.expr"
                      :label="item.expr"
                      @change="autoFixCrontab">{{ item.name }}</el-checkbox>
                  </template>
                </el-checkbox-group>
              </el-form-item>

              <el-form-item :label="$t('Days')">
                <el-checkbox-group v-model="formCrontab.days">
                  <template v-for="(item, index) in DAYS">
                    <br v-if="item === 'sep'">
                    <el-checkbox v-else
                      border
                      class="crontab-item-checkbox"
                      :key="item.expr"
                      :label="item.expr"
                      @change="autoFixCrontab">{{ item.name }}</el-checkbox>
                  </template>
                </el-checkbox-group>
              </el-form-item>

              <el-form-item :label="$t('Months')">
                <el-checkbox-group v-model="formCrontab.months">
                  <template v-for="(item, index) in MONTHS">
                    <br v-if="item === 'sep'">
                    <el-checkbox v-else
                      border
                      class="crontab-item-checkbox"
                      :key="item.expr"
                      :label="item.expr"
                      @change="autoFixCrontab">{{ item.name }}</el-checkbox>
                  </template>
                </el-checkbox-group>
              </el-form-item>

              <el-form-item :label="$t('Weekdays')">
                <el-checkbox-group v-model="formCrontab.weeks">
                  <template v-for="(item, index) in WEEKS">
                    <br v-if="item === 'sep'">
                    <el-checkbox v-else
                      border
                      class="crontab-item-checkbox"
                      :key="item.expr"
                      :label="item.expr"
                      @change="autoFixCrontab">{{ item.name }}</el-checkbox>
                  </template>
                </el-checkbox-group>
              </el-form-item>

              <el-form-item label="Crontab">
                <code class="crontab-expr-parts crontab-expr-parts-minutes">{{ formCrontabExprParts.minutes }}</code>
                <code class="crontab-expr-parts crontab-expr-parts-hours">{{ formCrontabExprParts.hours }}</code>
                <code class="crontab-expr-parts crontab-expr-parts-days">{{ formCrontabExprParts.days }}</code>
                <code class="crontab-expr-parts crontab-expr-parts-months">{{ formCrontabExprParts.months }}</code>
                <code class="crontab-expr-parts crontab-expr-parts-weeks">{{ formCrontabExprParts.weeks }}</code>
              </el-form-item>
            </template>
            <el-form-item v-else label="固定 Crontab">
              <code class="crontab-expr-parts crontab-expr-parts-minutes">{{ fixedCrontabExprParts.minutes }}</code>
              <code class="crontab-expr-parts crontab-expr-parts-hours">{{ fixedCrontabExprParts.hours }}</code>
              <code class="crontab-expr-parts crontab-expr-parts-days">{{ fixedCrontabExprParts.days }}</code>
              <code class="crontab-expr-parts crontab-expr-parts-months">{{ fixedCrontabExprParts.months }}</code>
              <code class="crontab-expr-parts crontab-expr-parts-weeks">{{ fixedCrontabExprParts.weeks }}</code>
            </el-form-item>
            <!-- Crontab配置结束 -->

            <el-form-item :label="$t('Expires')" prop="expireTime">
              <el-date-picker
                v-model="form.expireTime"
                type="datetime"
                align="left"
                format="yyyy-MM-dd HH:mm"
                :clearable="true"
                :picker-options="datetimePickerOptions">
              </el-date-picker>
            </el-form-item>

            <el-form-item :label="$t('Note')">
              <el-input :placeholder="$t('Optional')"
                type="textarea"
                resize="none"
                :autosize="{minRows: 2}"
                maxlength="5000"
                v-model="form.note"></el-input>
            </el-form-item>

            <el-form-item class="setup-footer">
              <el-button class="danger-button float-left" v-if="pageMode === 'setup'" @click="deleteData">{{ $t('Delete') }}</el-button>
              <el-button type="primary" v-prevent-re-click @click="submitData">{{ $t('Save') }}</el-button>
            </el-form-item>
          </el-form>
        </div>
      </el-main>
    </el-container>
  </el-dialog>
</template>

<script>
export default {
  name: 'CrontabConfigSetup',
  components: {
  },
  watch: {
    'form.id'(val) {
      if (val && (val.length < this.ID_PREFIX.length || val.indexOf(this.ID_PREFIX) < 0)) {
        this.form.id = this.ID_PREFIX;
      }
    },
    show(val) {
      if (!val) {
        this.$root.$emit('reload.crontabConfigList');
      }
    },
    useCustomId(val) {
      if (val) {
        this.form.id = `${this.ID_PREFIX}my-crontab`;
      } else {
        this.form.id = null;
      }
    },
  },
  methods: {
    async loadData(id) {
      if (!id) {
        this.pageMode = 'add';
        const defaultFormCrontab = {
          weeks  : ['*'],
          months : ['*'],
          days   : ['*'],
          hours  : ['*'],
          minutes: ['*/5'],
        };
        this.formCrontabCache = this.T.jsonCopy(defaultFormCrontab);
        this.formCrontab      = this.T.jsonCopy(defaultFormCrontab);
        this.T.jsonClear(this.form);
        this.form.taskRecordLimit = this.$store.getters.SYSTEM_INFO('_TASK_RECORD_FUNC_LIMIT_BY_ORIGIN_CRONTAB_CONFIG');
        this.data = {};

      } else {
        this.pageMode = 'setup';
        this.data.id = id;

        let apiRes = await this.T.callAPI_getOne('/api/v1/crontab-configs/do/list', this.data.id);
        if (!apiRes || !apiRes.ok) return;

        this.data = apiRes.data;

        let nextForm = {};
        Object.keys(this.form).forEach(f => nextForm[f] = this.data[f]);
        nextForm.funcCallKwargsJSON = JSON.stringify(nextForm.funcCallKwargsJSON, null, 2);
        nextForm.tagsJSON = nextForm.tagsJSON || [];

        if (this.T.isNothing(nextForm.taskRecordLimit)) {
          nextForm.taskRecordLimit = this.$store.getters.SYSTEM_INFO('_TASK_RECORD_FUNC_LIMIT_BY_ORIGIN_CRONTAB_CONFIG')
        }

        this.form = nextForm;

        if (this.data.crontab) {
          // 拆分Crontab
          this.data.crontab.split(' ').forEach((d, index) => {
            let f = this.CRONTAB_PARTS_MAP[index];
            this.formCrontab[f] = d.split(',');
          });
          this.formCrontabCache = this.T.jsonCopy(this.formCrontab);
        }
      }

      // 获取函数列表
      let funcList = await this.common.getFuncList();

      for (var funcId in funcList.map) {
        let f = funcList.map[funcId];
        f.isFixedCrontab = !!(f.extraConfigJSON && f.extraConfigJSON.fixedCrontab);
        if (f.isFixedCrontab) {
          f.label += ' ' + this.$t('(Fixed Crontab)');
        }
      }

      this.funcMap      = funcList.map;
      this.funcCascader = funcList.cascader;

      this.show = true;
    },
    async submitData() {
      try {
        await this.$refs.form.validate();
      } catch(err) {
        return console.error(err);
      }

      switch(this.pageMode) {
        case 'add':
          return await this.addData();
        case 'setup':
          return await this.modifyData();
      }
    },
    async addData() {
      let _formData = this.T.jsonCopy(this.form);
      let opt = {
        body : { data: _formData },
        alert: { okMessage: this.$t('Crontab Config created') },
      };

      // 添加函数调用参数kwargsJSON
      try {
        opt.body.data.funcCallKwargsJSON = JSON.parse(this.form.funcCallKwargsJSON);
      } catch(err) {
        return this.T.alert(`${this.$t('Invalid argument format')}<br>${err.toString()}`);
      }

      if (!this.fixedCrontabExpr) {
        // 添加Crontab表达式
        opt.body.data.crontab = this.formCrontabExpr.trim() || null;
      }

      let apiRes = await this.T.callAPI('post', '/api/v1/crontab-configs/do/add', opt);
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateHighlightedTableDataId', apiRes.data.id);
      this.show = false;
    },
    async modifyData() {
      let _formData = this.T.jsonCopy(this.form);
      delete _formData.id;

      let opt = {
        params: { id: this.data.id },
        body  : { data: _formData },
        alert : { okMessage: this.$t('Crontab Config saved') },
      };

      // 添加函数调用参数kwargsJSON
      try {
        opt.body.data.funcCallKwargsJSON = JSON.parse(this.form.funcCallKwargsJSON);
      } catch(err) {
        return this.T.alert(`${this.$t('Invalid argument format')}<br>${err.toString()}`);
      }

      if (!this.fixedCrontabExpr) {
        // 添加Crontab表达式
        opt.body.data.crontab = this.formCrontabExpr.trim() || null;
      }

      let apiRes = await this.T.callAPI('post', '/api/v1/crontab-configs/:id/do/modify', opt);
      if (!apiRes || !apiRes.ok) return;

      this.$store.commit('updateHighlightedTableDataId', apiRes.data.id);
      this.show = false;
    },
    async deleteData() {
      if (!await this.T.confirm(this.$t('Are you sure you want to delete the Crontab Config?'))) return;

      let apiRes = await this.T.callAPI('/api/v1/crontab-configs/:id/do/delete', {
        params: { id: this.data.id },
        alert : { okMessage: this.$t('Crontab Config deleted') },
      });
      if (!apiRes || !apiRes.ok) return;

      this.show = false;
    },
    autoFillFuncCallKwargsJSON(funcId) {
      // 自动填充调用参数
      let parameters = this.funcMap[funcId].argsJSON
                    || Object.keys(this.funcMap[funcId].kwargsJSON);

      let example = {};
      parameters.forEach(p => {
        if (p.indexOf('**') === 0) {
          // 暂定：不展示**kwargs参数
        } else {
          example[p] = p.toUpperCase();
        }
      });

      this.form.funcCallKwargsJSON = JSON.stringify(example, null, 2);
    },
    removeTag(tag) {
      this.form.tagsJSON.splice(this.form.tagsJSON.indexOf(tag), 1);
    },
    openAddTagInput() {
      this.showAddTag = true;
      this.$nextTick(_ => {
        this.$refs.newTag.$refs.input.focus();
      });
    },
    addTag() {
      let newTag = this.newTag;
      if (newTag) {
        if (!Array.isArray(this.form.tagsJSON)) {
          this.$set(this.form, 'tagsJSON', []);
        }
        this.form.tagsJSON.push(newTag);
      }
      this.showAddTag = false;
      this.newTag     = '';
    },
    autoFixCrontab() {
      let sortFunc = (a, b) => {
        return parseInt(a) - parseInt(b);
      }
      let hasStarExpr = part => {
        if (this.T.isNothing(part)) return false;
        for (let i = 0; i < part.length; i++) {
          if (part[i].indexOf('*') >= 0) return true;
        }
        return false;
      }

      ['weeks', 'months', 'days', 'hours', 'minutes'].forEach(part => {
        let defaultExpr = this[part.toUpperCase()][0].expr;

        let oldPart = this.formCrontabCache[part];
        let newPart = this.formCrontab[part];
        if (oldPart.length + newPart.length > 0 && oldPart.join(',') === newPart.join(',')) return;

        if (newPart.length <= 0) {
          this.formCrontab[part] = [defaultExpr];
        } else if (hasStarExpr(newPart)) {
          this.formCrontab[part] = [newPart.pop()];
        }

        this.formCrontabCache[part].sort(sortFunc);
        this.formCrontab[part].sort(sortFunc);
      });

      this.formCrontabCache = this.T.jsonCopy(this.formCrontab);
    },
    getNumberList(fixedItems, start, end, step, wrapEach) {
      step = step || 1;

      let list = fixedItems || [];
      let count = 0;
      for (let i = start; i <= end; i+=step) {
        count++;
        list.push({
          expr: i.toString(),
          name: this.T.padZero(i, 2),
        });

        if (count % wrapEach === 0) {
          list.push('sep');
        }
      }
      return list;
    },
  },
  computed: {
    ID_PREFIX() {
      return 'cron-';
    },
    CRONTAB_PARTS_MAP() {
      return {
        0: 'minutes',
        1: 'hours',
        2: 'days',
        3: 'months',
        4: 'weeks',
      };
    },
    WEEKS() {
      return [
        {expr: '*', name: this.$t('Every weekday')},
        'sep',
        {expr: '1', name: this.$t('MON')},
        {expr: '2', name: this.$t('TUE')},
        {expr: '3', name: this.$t('WED')},
        {expr: '4', name: this.$t('THU')},
        {expr: '5', name: this.$t('FRI')},
        'sep',
        {expr: '6', name: this.$t('SAT')},
        {expr: '0', name: this.$t('SUN')},
      ];
    },
    MONTHS() {
      return this.getNumberList([
        {expr: '*', name: this.$t('Every month')},
        'sep',
        {expr: '*/3', name: this.$t('Every 3 months')},
        {expr: '*/6', name: this.$t('Every 6 months')},
        'sep',
      ], 1, 12, 1, 6);
    },
    DAYS() {
      return this.getNumberList([
        {expr: '*', name: this.$t('Every day')},
        'sep',
      ], 1, 31, 1, 5);
    },
    HOURS() {
      return this.getNumberList([
        {expr: '*', name: this.$t('Every hour')},
        'sep',
        {expr: '*/2', name: this.$t('Every 2 hours')},
        {expr: '*/3', name: this.$t('Every 3 hours')},
        {expr: '*/6', name: this.$t('Every 6 hours')},
        'sep',
      ], 0, 23, 1, 6);
    },
    MINUTES() {
      return this.getNumberList([
        {expr: '*', name: this.$t('Every minute')},
        'sep',
        {expr: '*/5', name: this.$t('Every 5 minutes')},
        {expr: '*/15', name: this.$t('Every 15 minutes')},
        {expr: '*/30', name: this.$t('Every 30 minutes')},
        'sep',
      ], 0, 59, 5, 6);
    },

    pageTitle() {
      const _map = {
        setup: this.$t('Setup Crontab Config'),
        add  : this.$t('Add Crontab Config'),
      };
      return _map[this.pageMode];
    },
    apiCustomKwargsSupport() {
      let funcId = this.form.funcId;
      if (!funcId) return false;
      if (!this.funcMap[funcId]) return false;

      for (let k in this.funcMap[funcId].kwargsJSON) {
        if (k.indexOf('**') === 0) return true;
      }
      return false;
    },
    fixedCrontabExpr() {
      let selectedFunc = this.funcMap[this.form.funcId];
      if (selectedFunc
          && selectedFunc.extraConfigJSON
          && selectedFunc.extraConfigJSON.fixedCrontab) {
        return selectedFunc.extraConfigJSON.fixedCrontab;
      } else {
        return null;
      }
    },
    fixedCrontabExprParts() {
      if (!this.fixedCrontabExpr) {
        return null;
      } else {
        let _parts = this.fixedCrontabExpr.split(' ');
        return {
          weeks  : _parts[4],
          months : _parts[3],
          days   : _parts[2],
          hours  : _parts[1],
          minutes: _parts[0],
        };
      }
    },
    formCrontabExprParts() {
      return {
        weeks  : this.formCrontab.weeks.join(','),
        months : this.formCrontab.months.join(','),
        days   : this.formCrontab.days.join(','),
        hours  : this.formCrontab.hours.join(','),
        minutes: this.formCrontab.minutes.join(','),
      };
    },
    formCrontabExpr() {
      return [
        this.formCrontabExprParts.minutes,
        this.formCrontabExprParts.hours,
        this.formCrontabExprParts.days,
        this.formCrontabExprParts.months,
        this.formCrontabExprParts.weeks,
      ].join(' ').trim();
    },
    datetimePickerOptions() {
      const now = new Date().getTime();
      const shortcutDaysList = [1, 3, 7, 30, 90, 365];
      let shortcuts = [];
      shortcutDaysList.forEach((days) => {
        const date = new Date();
        date.setTime(now + 3600 * 24 * days * 1000);

        shortcuts.push({
          text: this.$tc('shortcutDays', days),
          onClick(picker) {
            picker.$emit('pick', date)
          }
        });
      });

      return {
        shortcuts: shortcuts
      }
    },
  },
  props: {
  },
  data() {
    let errorMessage_funcCallKwargsJSON = this.$t('Please input arguments, input "{}" when no argument');

    return {
      show    : false,
      pageMode: null,

      data        : {},
      funcMap     : {},
      funcCascader: [],

      useCustomId: false,
      showAddTag : false,
      newTag     : '',

      form: {
        id                : null,
        funcId            : null,
        funcCallKwargsJSON: null,
        tagsJSON          : [],
        expireTime        : null,
        taskRecordLimit   : this.$store.getters.SYSTEM_INFO('_TASK_RECORD_FUNC_LIMIT_BY_ORIGIN_CRONTAB_CONFIG'),
        note              : null,
        // crontab 单独处理
      },

      formCrontabCache: {
        weeks  : [],
        months : [],
        days   : [],
        hours  : [],
        minutes: [],
      },
      formCrontab: {
        weeks  : [],
        months : [],
        days   : [],
        hours  : [],
        minutes: [],
      },

      formRules: {
        id: [
          {
            trigger: 'change',
            validator: (rule, value, callback) => {
              if (this.T.notNothing(value)) {
                if ((value.indexOf(this.ID_PREFIX) !== 0 || value === this.ID_PREFIX)) {
                  return callback(new Error(this.$t('ID must starts with "{prefix}"', { prefix: this.ID_PREFIX })));
                }
                if (!value.match(/^[0-9a-zA-Z\.\-\_]+$/g)) {
                  return callback(new Error(this.$t('Only numbers, alphabets, dot(.), underscore(_) and hyphen(-) are allowed')));
                }
              }
              return callback();
            },
          }
        ],
        funcId: [
          {
            trigger : 'blur',
            message : this.$t('Please select Func'),
            required: true,
          },
        ],
        expireTime: [
          {
            trigger: 'change',
            message  : this.$t('Only date-time between 1970 and 2037 are allowed'),
            validator: (rule, value, callback) => {
              if (value) {
                let ts = this.M(value).unix();
                if (ts < this.T.MIN_UNIX_TIMESTAMP) {
                  return callback(new Error(this.$t('Date-time cannot earlier than 1970')));
                } else if (ts > this.T.MAX_UNIX_TIMESTAMP) {
                  return callback(new Error(this.$t('Date-time cannot later than 2037')));
                }
              }
              return callback();
            },
          }
        ],
        funcCallKwargsJSON: [
          {
            trigger : 'blur',
            message : errorMessage_funcCallKwargsJSON,
            required: true,
          },
          {
            trigger  : 'change',
            validator: (rule, value, callback) => {
              try {
                if (value) {
                  let j = JSON.parse(value);
                  if (Array.isArray(j)) {
                    return callback(new Error(errorMessage_funcCallKwargsJSON));
                  }
                }
                return callback();

              } catch(err) {
                return callback(new Error(errorMessage_funcCallKwargsJSON));
              }
            },
          }
        ],
      }
    }
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.task-record-limit-input {
  width: 180px;
}
.task-record-limit-prefix {
  color: grey;
  padding-right: 10px;
}
.task-record-limit-unit {
  color: grey;
  padding-left: 10px;
}
.task-record-limit-unit > span {
  width: 35px;
  display: inline-block;
}
.task-record-limit-clear {
  float: right
}
.crontab-expr-parts {
  font-size: xx-large;
  margin-right: 20px;
}
.crontab-expr-parts-weeks {
  color: brown;
}
.crontab-expr-parts-months {
  color: red;
}
.crontab-expr-parts-days {
  color: seagreen;
}
.crontab-expr-parts-hours {
  color: magenta;
}
.crontab-expr-parts-minutes {
  color: orange;
}

.el-checkbox.crontab-item-checkbox {
  margin-left : 5px !important;
  margin-right: 0 !important;
  min-width: 75px;
}
</style>
