<i18n locale="zh-CN" lang="yaml">
Experimental Features that have not been officially released can be enabled here, configuration is only saved locally in the browser.: 一些尚未正式公开的实验性功能可在本页面开启，本页面配置仅保存在浏览器本地

Enable PIP Tool: 启用 PIP 工具
For installing 3rd-party Python package: 用于安装第三方 Python 包
Once enabled, it can be accessed from Management page {0} PIP tool: 启用后，可在「管理」{0}「PIP 工具」进入

Enable File Manage: 启用文件管理
For managing files on the server side: 用于管理服务器端文件
Once enabled, it can be accessed from Management page {0} File Manage: 启用后，可在「管理」{0}「文件管理」进入

Enable File Service: 启用文件服务
For serving resource directories as file services: 用于将资源目录提供为文件服务
Once enabled, it can be accessed from Management page {0} File Service: 启用后，可在「管理」{0}「文件服务」进入

Enable Func Cache Manage: 启用函数缓存管理
For managing cached data from Scripts: 用于管理脚本产生的缓存数据
Once enabled, it can be accessed from Management page {0} Func Cache Manage: 启用后，可在「管理」{0}「函数缓存管理」进入

Enable Func Store Manage: 启用函数存储管理
For managing stored data from Scripts: 用于管理脚本产生的存储数据
Once enabled, it can be accessed from Management page {0} Func Store Manage: 启用后，可在「管理」{0}「函数存储管理」进入

Enable Func Doc: 启用函数文档
Document page for all exported Python functions and Auth Links: 函数的文档，包含所有导出的 Python 函数和授权链接
Once enabled, it can be accessed from Management page {0} Func Doc / Auth Link Doc: 启用后，可在「管理」{0}「函数文档 / 授权链接文档」进入

Enable Open API Doc: 启用 Open API 文档
Document page for Open API powered by Swagger: 基于 Swagger 的 Open API 文档
Once enabled, it can be accessed from Management page {0} Open API Doc: 启用后，可在「管理」{0}「Open API 文档」进入

Enable System Status Page: 启用系统状态查看页面
Status Page for current system: 本系统状态查看页面
Once enabled, it can be accessed from Management page {0} System Status: 启用后，可在「管理」{0}「系统状态」进入

Enable System Log Page: 启用系统日志查看页面
Log Page for current system: 本系统日志查看页面
Once enabled, it can be accessed from Management page {0} System Logs: 启用后，可在「管理」{0}「系统日志」进入

Enable Abnormal Request Page: 启用异常请求查看页面
Abnormal Request Page for current system: 本系统异常请求查看页面
Once enabled, it can be accessed from Management page {0} Abnormal Requests: 启用后，可在「管理」{0}「异常请求」进入

Enable Script Log Page: 启用脚本日志查看页面
Log Page for Script runtime: 脚本运行时日志查看页面
Once enabled, it can be accessed from Management page {0} Script Logs: 启用后，可在「管理」{0}「脚本日志」进入

Enable Script Failure Page: 启用脚本故障查看页面
Failure Page for Script runtime: 脚本运行时故障查看页面
Once enabled, it can be accessed from Management page {0} Script Failures: 启用后，可在「管理」{0}「脚本故障」进入

Enable Access Key Manage: 启用 Access Key 管理
For allowing external systems to call the Open APIs of this system: 用于管理允许外部系统调用本系统的 Open API
Once enabled, it can be accessed from Management page {0} Access Keys: 启用后，可在「管理」{0}「Access Keys」进入
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Abnormal Request Page for current system: 本系統異常請求查看頁面
Document page for Open API powered by Swagger: 基於 Swagger 的 Open API 文檔
Document page for all exported Python functions and Auth Links: 函數的文檔，包含所有導出的 Python 函數和授權鏈接
Enable Abnormal Request Page: 啓用異常請求查看頁面
Enable Access Key Manage: 啓用 Access Key 管理
Enable File Manage: 啓用文件管理
Enable File Service: 啓用文件服務
Enable Func Cache Manage: 啓用函數緩存管理
Enable Func Doc: 啓用函數文檔
Enable Func Store Manage: 啓用函數存儲管理
Enable Open API Doc: 啓用 Open API 文檔
Enable PIP Tool: 啓用 PIP 工具
Enable Script Failure Page: 啓用腳本故障查看頁面
Enable Script Log Page: 啓用腳本日誌查看頁面
Enable System Log Page: 啓用系統日誌查看頁面
Enable System Status Page: 啓用系統狀態查看頁面
? Experimental Features that have not been officially released can be enabled here, configuration is only saved locally in the browser.
: 一些尚未正式公開的實驗性功能可在本頁面開啓，本頁面配置僅保存在瀏覽器本地
Failure Page for Script runtime: 腳本運行時故障查看頁面
For allowing external systems to call the Open APIs of this system: 用於管理允許外部系統調用本系統的 Open API
For installing 3rd-party Python package: 用於安裝第三方 Python 包
For managing cached data from Scripts: 用於管理腳本產生的緩存數據
For managing files on the server side: 用於管理服務器端文件
For managing stored data from Scripts: 用於管理腳本產生的存儲數據
For serving resource directories as file services: 用於將資源目錄提供為文件服務
Log Page for Script runtime: 腳本運行時日誌查看頁面
Log Page for current system: 本系統日誌查看頁面
Once enabled, it can be accessed from Management page {0} Abnormal Requests: 啓用後，可在「管理」{0}「異常請求」進入
Once enabled, it can be accessed from Management page {0} Access Keys: 啓用後，可在「管理」{0}「Access Keys」進入
Once enabled, it can be accessed from Management page {0} File Manage: 啓用後，可在「管理」{0}「文件管理」進入
Once enabled, it can be accessed from Management page {0} File Service: 啓用後，可在「管理」{0}「文件服務」進入
Once enabled, it can be accessed from Management page {0} Func Cache Manage: 啓用後，可在「管理」{0}「函數緩存管理」進入
Once enabled, it can be accessed from Management page {0} Func Doc / Auth Link Doc: 啓用後，可在「管理」{0}「函數文檔 / 授權鏈接文檔」進入
Once enabled, it can be accessed from Management page {0} Func Store Manage: 啓用後，可在「管理」{0}「函數存儲管理」進入
Once enabled, it can be accessed from Management page {0} Open API Doc: 啓用後，可在「管理」{0}「Open API 文檔」進入
Once enabled, it can be accessed from Management page {0} PIP tool: 啓用後，可在「管理」{0}「PIP 工具」進入
Once enabled, it can be accessed from Management page {0} Script Failures: 啓用後，可在「管理」{0}「腳本故障」進入
Once enabled, it can be accessed from Management page {0} Script Logs: 啓用後，可在「管理」{0}「腳本日誌」進入
Once enabled, it can be accessed from Management page {0} System Logs: 啓用後，可在「管理」{0}「系統日誌」進入
Once enabled, it can be accessed from Management page {0} System Status: 啓用後，可在「管理」{0}「系統狀態」進入
Status Page for current system: 本系統狀態查看頁面
</i18n>
<i18n locale="zh-TW" lang="yaml">
Abnormal Request Page for current system: 本系統異常請求檢視頁面
Document page for Open API powered by Swagger: 基於 Swagger 的 Open API 文件
Document page for all exported Python functions and Auth Links: 函式的文件，包含所有匯出的 Python 函式和授權連結
Enable Abnormal Request Page: 啟用異常請求檢視頁面
Enable Access Key Manage: 啟用 Access Key 管理
Enable File Manage: 啟用檔案管理
Enable File Service: 啟用檔案服務
Enable Func Cache Manage: 啟用函式快取管理
Enable Func Doc: 啟用函式文件
Enable Func Store Manage: 啟用函式儲存管理
Enable Open API Doc: 啟用 Open API 文件
Enable PIP Tool: 啟用 PIP 工具
Enable Script Failure Page: 啟用指令碼故障檢視頁面
Enable Script Log Page: 啟用指令碼日誌檢視頁面
Enable System Log Page: 啟用系統日誌檢視頁面
Enable System Status Page: 啟用系統狀態檢視頁面
? Experimental Features that have not been officially released can be enabled here, configuration is only saved locally in the browser.
: 一些尚未正式公開的實驗性功能可在本頁面開啟，本頁面配置僅儲存在瀏覽器本地
Failure Page for Script runtime: 指令碼執行時故障檢視頁面
For allowing external systems to call the Open APIs of this system: 用於管理允許外部系統呼叫本系統的 Open API
For installing 3rd-party Python package: 用於安裝第三方 Python 包
For managing cached data from Scripts: 用於管理指令碼產生的快取資料
For managing files on the server side: 用於管理伺服器端檔案
For managing stored data from Scripts: 用於管理指令碼產生的儲存資料
For serving resource directories as file services: 用於將資源目錄提供為檔案服務
Log Page for Script runtime: 指令碼執行時日誌檢視頁面
Log Page for current system: 本系統日誌檢視頁面
Once enabled, it can be accessed from Management page {0} Abnormal Requests: 啟用後，可在「管理」{0}「異常請求」進入
Once enabled, it can be accessed from Management page {0} Access Keys: 啟用後，可在「管理」{0}「Access Keys」進入
Once enabled, it can be accessed from Management page {0} File Manage: 啟用後，可在「管理」{0}「檔案管理」進入
Once enabled, it can be accessed from Management page {0} File Service: 啟用後，可在「管理」{0}「檔案服務」進入
Once enabled, it can be accessed from Management page {0} Func Cache Manage: 啟用後，可在「管理」{0}「函式快取管理」進入
Once enabled, it can be accessed from Management page {0} Func Doc / Auth Link Doc: 啟用後，可在「管理」{0}「函式文件 / 授權連結文件」進入
Once enabled, it can be accessed from Management page {0} Func Store Manage: 啟用後，可在「管理」{0}「函式儲存管理」進入
Once enabled, it can be accessed from Management page {0} Open API Doc: 啟用後，可在「管理」{0}「Open API 文件」進入
Once enabled, it can be accessed from Management page {0} PIP tool: 啟用後，可在「管理」{0}「PIP 工具」進入
Once enabled, it can be accessed from Management page {0} Script Failures: 啟用後，可在「管理」{0}「指令碼故障」進入
Once enabled, it can be accessed from Management page {0} Script Logs: 啟用後，可在「管理」{0}「指令碼日誌」進入
Once enabled, it can be accessed from Management page {0} System Logs: 啟用後，可在「管理」{0}「系統日誌」進入
Once enabled, it can be accessed from Management page {0} System Status: 啟用後，可在「管理」{0}「系統狀態」進入
Status Page for current system: 本系統狀態檢視頁面
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <transition name="fade">
    <el-container direction="vertical" v-show="$store.state.isLoaded">
      <!-- 标题区 -->
      <el-header height="60px">
        <h1>
          {{ $t('Experimental Features') }}
        </h1>
      </el-header>

      <!-- 编辑区 -->
      <el-main>
        <el-row :gutter="20">
          <el-col :span="15">
            <div class="setup-form">
              <el-form ref="form" :model="form" label-width="0px">
                <el-form-item>
                  <InfoBlock type="info" :title="$t('Experimental Features that have not been officially released can be enabled here, configuration is only saved locally in the browser.')" />
                </el-form-item>

                <el-form-item prop="PIPTool">
                  <el-switch :active-text="$t('Enable PIP Tool')" v-model="form.PIPTool"></el-switch>
                  <div class="text-small form-item-tip">
                    {{ $t('For installing 3rd-party Python package') }}
                    <br><i18n path="Once enabled, it can be accessed from Management page {0} PIP tool"><i class="fa fa-fw fa-long-arrow-right"></i></i18n>
                  </div>
                </el-form-item>

                <el-form-item prop="FileManage">
                  <el-switch :active-text="$t('Enable File Manage')" v-model="form.FileManage"></el-switch>
                  <div class="text-small form-item-tip">
                    {{ $t('For managing files on the server side') }}
                    <br><i18n path="Once enabled, it can be accessed from Management page {0} File Manage"><i class="fa fa-fw fa-long-arrow-right"></i></i18n>
                  </div>
                </el-form-item>

                <el-form-item prop="FileService">
                  <el-switch :active-text="$t('Enable File Service')" v-model="form.FileService"></el-switch>
                  <div class="text-small form-item-tip">
                    {{ $t('For serving resource directories as file services') }}
                    <br><i18n path="Once enabled, it can be accessed from Management page {0} File Service"><i class="fa fa-fw fa-long-arrow-right"></i></i18n>
                  </div>
                </el-form-item>

                <el-form-item prop="FuncCacheManage">
                  <el-switch :active-text="$t('Enable Func Cache Manage')" v-model="form.FuncCacheManage"></el-switch>
                  <div class="text-small form-item-tip">
                    {{ $t('For managing cached data from Scripts') }}
                    <br><i18n path="Once enabled, it can be accessed from Management page {0} Func Cache Manage"><i class="fa fa-fw fa-long-arrow-right"></i></i18n>
                  </div>
                </el-form-item>
                <el-form-item prop="FuncStoreManage">
                  <el-switch :active-text="$t('Enable Func Store Manage')" v-model="form.FuncStoreManage"></el-switch>
                  <div class="text-small form-item-tip">
                    {{ $t('For managing stored data from Scripts') }}
                    <br><i18n path="Once enabled, it can be accessed from Management page {0} Func Store Manage"><i class="fa fa-fw fa-long-arrow-right"></i></i18n>
                  </div>
                </el-form-item>

                <el-form-item prop="FuncDoc">
                  <el-switch :active-text="$t('Enable Func Doc')" v-model="form.FuncDoc"></el-switch>
                  <div class="text-small form-item-tip">
                    {{ $t('Document page for all exported Python functions and Auth Links') }}
                    <br><i18n path="Once enabled, it can be accessed from Management page {0} Func Doc / Auth Link Doc"><i class="fa fa-fw fa-long-arrow-right"></i></i18n>
                  </div>
                </el-form-item>

                <el-form-item prop="OpenAPIDoc">
                  <el-switch :active-text="$t('Enable Open API Doc')" v-model="form.OpenAPIDoc"></el-switch>
                  <div class="text-small form-item-tip">
                    {{ $t('Document page for Open API powered by Swagger') }}
                    <br><i18n path="Once enabled, it can be accessed from Management page {0} Open API Doc"><i class="fa fa-fw fa-long-arrow-right"></i></i18n>
                  </div>
                </el-form-item>

                <el-form-item prop="AccessKeys" v-if="$store.getters.isAdmin">
                  <el-switch :active-text="$t('Enable Access Key Manage')" v-model="form.AccessKeys"></el-switch>
                  <div class="text-small form-item-tip">
                    {{ $t('For allowing external systems to call the Open APIs of this system') }}
                    <br><i18n path="Once enabled, it can be accessed from Management page {0} Access Keys"><i class="fa fa-fw fa-long-arrow-right"></i></i18n>
                  </div>
                </el-form-item>
              </el-form>
            </div>
          </el-col>
          <el-col :span="9" class="hidden-md-and-down">
          </el-col>
        </el-row>
      </el-main>
    </el-container>
  </transition>
</template>

<script>
export default {
  name: 'ExperimentalFeatures',
  components: {
  },
  watch: {
    $route: {
      immediate: true,
      async handler(to, from) {
        await this.loadData();
      }
    },
    form: {
      deep: true,
      handler(to, from) {
        let _formData = this.T.jsonCopy(this.form);
        this.$store.commit('updateEnabledExperimentalFeatures', _formData);
      }
    },
  },
  methods: {
    async loadData() {
      let _featureMap = this.T.jsonCopy(this.$store.state.enabledExperimentalFeatureMap) || {};

      let nextForm = {};
      Object.keys(this.form).forEach(f => nextForm[f] = !!_featureMap[f]);
      this.form = nextForm;

      this.$store.commit('updateLoadStatus', true);
    },
  },
  computed: {
  },
  props: {
  },
  data() {
    return {
      form: {
        PIPTool        : false,
        FileManage     : false,
        FileService    : false,
        FuncCacheManage: false,
        FuncStoreManage: false,
        FuncDoc        : false,
        OpenAPIDoc     : false,
        AccessKeys     : false,
      },
    }
  },
}
</script>

<style scoped>
</style>
