<i18n locale="en" lang="yaml">
generalCount        : '{n}'
generalCountUnit    : ' '
recentOperationCount: '(Latest {n} Operation) | (Latest {n} Operations)'
</i18n>

<i18n locale="zh-CN" lang="yaml">
'Current browser-server time difference:': '当前浏览器与服务器时差：'

generalCount        : '{n} 个'
generalCountUnit    : ' 个'
recentOperationCount: 最近 {n} 条

Expand All             : 展开所有服务
Collapse And Categorize: 折叠并归类

Overview         : 总览
Services         : 服务
Hostname         : 主机名
Process ID       : 进程 ID
Up Time          : 已运行
Up Time AVG      : 平均已运行
Up Time MAX      : 最长已运行
Up Time MIN      : 最短已运行
Queues           : 队列
Worker Queues    : 工作队列
Worker           : 工作单元
Process          : 工作进程
Task             : 任务
Jam              : 拥堵
Biz Entity       : 业务实体
Recent operations: 最近操作记录
Client           : 客户端
Client ID        : 客户端 ID
IP Address       : IP 地址
Operation        : 操作
Data ID          : 数据 ID
MODIFY           : 修改操作
DELETE           : 删除操作
Cost             : 耗时
Request          : 请求
Response         : 响应
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Biz Entity: 業務實體
Client: 客户端
Client ID: 客户端 ID
Collapse And Categorize: 摺疊並歸類
Cost: 耗時
'Current browser-server time difference:': 當前瀏覽器與服務器時差：
DELETE: 刪除操作
Data ID: 數據 ID
Expand All: 展開所有服務
Hostname: 主機名
IP Address: IP 地址
Jam: 擁堵
MODIFY: 修改操作
Operation: 操作
Overview: 總覽
Process: 工作進程
Process ID: 進程 ID
Queues: 隊列
Recent operations: 最近操作記錄
Request: 請求
Response: 響應
Services: 服務
Task: 任務
Up Time: 已運行
Up Time AVG: 平均已運行
Up Time MAX: 最長已運行
Up Time MIN: 最短已運行
Worker: 工作單元
Worker Queues: 工作隊列
generalCount: '{n} 個'
generalCountUnit: ' 個'
recentOperationCount: 最近 {n} 條
</i18n>
<i18n locale="zh-TW" lang="yaml">
Biz Entity: 業務實體
Client: 客戶端
Client ID: 客戶端 ID
Collapse And Categorize: 摺疊並歸類
Cost: 耗時
'Current browser-server time difference:': 當前瀏覽器與伺服器時差：
DELETE: 刪除操作
Data ID: 資料 ID
Expand All: 展開所有服務
Hostname: 主機名
IP Address: IP 地址
Jam: 擁堵
MODIFY: 修改操作
Operation: 操作
Overview: 總覽
Process: 工作程序
Process ID: 程序 ID
Queues: 佇列
Recent operations: 最近操作記錄
Request: 請求
Response: 響應
Services: 服務
Task: 任務
Up Time: 已執行
Up Time AVG: 平均已執行
Up Time MAX: 最長已執行
Up Time MIN: 最短已執行
Worker: 工作單元
Worker Queues: 工作佇列
generalCount: '{n} 個'
generalCountUnit: ' 個'
recentOperationCount: 最近 {n} 條
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <transition name="fade">
    <el-container direction="vertical" v-show="$store.state.isLoaded">
      <!-- 标题区 -->
      <el-header height="60px">
        <h1>{{ $t('Overview') }}</h1>
      </el-header>

      <!-- 列表区 -->
      <el-main>
        <span class="browser-server-time-diff" :class="browserServerTimeDiff > 1000 ? 'text-bad' : 'text-info'">
          <i class="fa fa-fw" :class="browserServerTimeDiff > 1000 ? 'fa-exclamation-triangle' : 'fa-exchange'"></i>
          {{ $t('Current browser-server time difference:') }}
          <TimeDuration :duration="browserServerTimeDiff" unit="ms" />
        </span>

        <el-divider content-position="left"><h1>{{ $t('Services') }} {{ $t('(') }}{{ $tc('generalCount', serviceInfo.length) }}{{ $t(')') }}</h1></el-divider>
        <div class="service-group-expand-button">
          <el-link @click="serviceGroupCollapsed = !serviceGroupCollapsed">
            <i class="fa fa-angle-left" :class="{ 'fa-flip-horizontal': !serviceGroupCollapsed }"></i><i class="fa fa-angle-left" :class="{ 'fa-flip-horizontal': serviceGroupCollapsed }" style="margin-left: 2px;"></i>
            {{ serviceGroupCollapsed ? $t('Expand All') : $t('Collapse And Categorize') }}
          </el-link>
        </div>
        <template v-for="group in [ serviceInfo_servers, serviceInfo_workers, serviceInfo_beat]">
          <div :class="{ 'service-group-collapsed': serviceGroupCollapsed }">
            <el-card
              class="service-card"
              :class="{ 'service-group-rest': serviceGroupCollapsed && i > 0 }"
              shadow="hover"
              v-for="service, i in group" :key="i">
              <div class="service-info">
                <span class="service-name">{{ service.name }}</span>
                <table>
                  <tr v-if="serviceGroupCollapsed && group.length > 1">
                    <td>{{ $t('Up Time AVG') }}</td>
                    <td>{{ $t(':') }}</td>
                    <td>{{ T.duration(serviceUptime_avg[service.name]) }}</td>
                  </tr>
                  <tr v-if="serviceGroupCollapsed && group.length > 1">
                    <td>{{ $t('Up Time MAX') }}</td>
                    <td>{{ $t(':') }}</td>
                    <td>{{ T.duration(serviceUptime_max[service.name]) }}</td>
                  </tr>
                  <tr v-if="serviceGroupCollapsed && group.length > 1">
                    <td>{{ $t('Up Time MIN') }}</td>
                    <td>{{ $t(':') }}</td>
                    <td>{{ T.duration(serviceUptime_min[service.name]) }}</td>
                  </tr>

                  <tr v-if="!serviceGroupCollapsed">
                    <td>{{ $t('Hostname') }}</td>
                    <td>{{ $t(':') }}</td>
                    <td><code>{{ service.hostname }}</code></td>
                  </tr>
                  <tr v-if="!serviceGroupCollapsed">
                    <td>{{ $t('Process ID') }}</td>
                    <td>{{ $t(':') }}</td>
                    <td><code>{{ service.pid }}</code></td>
                  </tr>
                  <tr v-if="!serviceGroupCollapsed || group.length === 1">
                    <td>{{ $t('Up Time') }}</td>
                    <td>{{ $t(':') }}</td>
                    <td>{{ T.duration(service.uptime * 1000) }}</td>
                  </tr>
                  <tr v-if="!serviceGroupCollapsed && service.queues">
                    <td>{{ $t('Queues')}}</td>
                    <td>{{ $t(':') }}</td>
                    <td><code>{{ service.queues.map(q => `#${q}`).join(' ') }}</code></td>
                  </tr>
                </table>

                <div class="service-active">
                  <el-progress :percentage="serviceGroupCollapsed ? 100 : service.activePercent" :format="serviceActiveFormat" :color="serviceActiveColor"></el-progress>
                </div>
              </div>
            </el-card>
            <el-card v-if="group.length > 0 && serviceGroupCollapsed" class="service-group-count">
              <span class="service-group-count-text">
                &times;
                {{ group.length }}
              </span>
            </el-card>
          </div>
        </template>

        <el-divider content-position="left"><h1>{{ $t('Worker Queues') }}</h1></el-divider>
        <el-card
          class="worker-queue-card"
          :class="{ 'worker-queue-highlight': workerQueue.taskCount > 0 }"
          shadow="hover"
          v-for="workerQueue, i in workerQueueInfo"
          :key="i">
          <div class="worker-queue-info">
            <span class="worker-queue-number">#{{ i }}</span>
            <table>
              <tr :class="{ 'text-bad': (workerQueue.workerCount <= 0) }">
                <td>{{ $t('Worker') }}</td>
                <td>{{ $t(':') }}</td>
                <td>{{ $tc('generalCount', workerQueue.workerCount) }}</td>
              </tr>
              <tr :class="{ 'text-bad': (workerQueue.processCount <= 0) }">
                <td>{{ $t('Process') }}</td>
                <td>{{ $t(':') }}</td>
                <td>{{ $tc('generalCount', workerQueue.processCount) }}</td>
              </tr>
              <tr :class="{ 'text-main': (workerQueue.taskCount > 0), 'text-good': (workerQueue.taskCount === 0) }">
                <td>{{ $t('Task') }}</td>
                <td>{{ $t(':') }}</td>
                <td>{{ $tc('generalCount', workerQueue.taskCount) }}</td>
              </tr>
            </table>
          </div>

          <el-progress type="circle" width="110"
            :percentage="workerQueueLoadPercentage(workerQueue.taskCount, workerQueue.processCount)"
            :format="workerQueueLoadFormat"
            :color="WORKER_QUEUE_TASK_COUNT_COLORS"></el-progress>
        </el-card>

        <el-divider content-position="left"><h1>{{ $t('Biz Entity') }}</h1></el-divider>
        <el-card class="biz-entity-card" shadow="hover" v-for="d in bizEntityInfo" :key="d.name">
          <i v-if="C.OVERVIEW_ENTITY_MAP.get(d.name).icon" class="fa fa-fw biz-entity-icon" :class="C.OVERVIEW_ENTITY_MAP.get(d.name).icon"></i>
          <i v-else-if="C.OVERVIEW_ENTITY_MAP.get(d.name).tagText" type="info" class="biz-entity-icon biz-entity-icon-text"><code>{{ C.OVERVIEW_ENTITY_MAP.get(d.name).tagText }}</code></i>

          <span class="biz-entity-name">{{ C.OVERVIEW_ENTITY_MAP.get(d.name).name }}</span>

          <template v-if="d.countEnabled">
            <span class="biz-entity-count">
              <el-tooltip effect="dark" :content="$t('Enabled')" placement="left">
                <span class="text-good">
                  {{ d.countEnabled }}
                </span>
              </el-tooltip>
              <span class="biz-entity-count-unit">{{ $t('generalCountUnit') }}</span>
            </span>
            <span class="biz-entity-count-sub">
              {{ $t('Total') }}{{ $t(':') }}
              {{ d.count }}
            </span>
          </template>

          <template v-else>
            <span class="biz-entity-count">
              {{ d.count }}
              <span class="biz-entity-count-unit">{{ $t('generalCountUnit') }}</span>
            </span>
          </template>
          </span>
        </el-card>

        <el-divider content-position="left">
          <h1>
            {{ $t('Recent operations') }}
            <small>{{ $t('(') }}{{ $tc('recentOperationCount', latestOperations.length) }}{{ $t(')') }}</small>
          </h1>
        </el-divider>
        <el-table :data="latestOperations">
          <el-table-column :label="$t('Time')" width="200">
            <template slot-scope="scope">
              <span>{{ scope.row.createTime | datetime }}</span>
              <br>
              <span class="text-info">{{ scope.row.createTime | fromNow }}</span>
            </template>
          </el-table-column>

          <el-table-column :label="$t('User')" width="350">
            <template slot-scope="scope">
              <strong>{{ scope.row.u_name || $t('Anonymity') }}</strong>

              <template v-if="scope.row.userId">
                <br>
                <span class="text-info">{{ $t('User ID') }}</span>
                &nbsp;<code class="text-main">{{ scope.row.userId }}</code>
                <CopyButton :content="scope.row.userId" />
              </template>

              <template v-if="T.notNothing(scope.row.clientIPsJSON)">
                <br>
                <span class="text-info">{{ $t('IP Address') }}</span>
                &nbsp;<code class="text-main">{{ scope.row.clientIPsJSON.join(', ') }}</code>
                <CopyButton :content="scope.row.clientIPsJSON.join(', ')" />
              </template>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Operation')">
            <template slot-scope="scope">
              <span class="text-good" v-if="scope.row.respStatusCode >= 200 && scope.row.respStatusCode < 400">
                <i class="fa fa-fw fa-check"></i>
              </span>
              <span class="text-bad" v-else>
                <i class="fa fa-fw fa-times"></i>
              </span>
              <span>{{ $t(scope.row.reqRouteName) }}</span>
              <strong v-if="T.endsWith(scope.row.reqRoute, '/do/modify')" class="text-watch">
                （{{ $t('MODIFY') }}）
              </strong>
              <strong v-if="T.endsWith(scope.row.reqRoute, '/do/delete')" class="text-bad">
                （{{ $t('DELETE') }}）
              </strong>

              <template v-if="scope.row._operationEntityId">
                <br>
                <i class="fa fa-fw"></i>
                <span class="text-info">{{ $t('Data ID') }}</span>
                &nbsp;<code class="text-main">{{ scope.row._operationEntityId }}</code>
                <CopyButton :content="scope.row._operationEntityId" />
              </template>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Cost')" align="right" width="100">
            <template slot-scope="scope">
              <TimeDuration :duration="scope.row.reqCost" unit="ms" />
            </template>
          </el-table-column>

          <el-table-column align="right" width="150">
            <template slot-scope="scope">
              <el-link type="primary" @click="showDetail(scope.row)">{{ $t('Show detail') }}</el-link>
            </template>
          </el-table-column>

        </el-table>
      </el-main>

      <LongTextDialog :showDownload="true" ref="longTextDialog" />
    </el-container>
  </transition>
</template>

<script>
import TimeDuration from '@/components/TimeDuration'
import LongTextDialog from '@/components/LongTextDialog'

export default {
  name: 'Overview',
  components: {
    TimeDuration,
    LongTextDialog,
  },
  watch: {
    $route: {
      immediate: true,
      async handler(to, from) {
        await this.loadData();
      }
    },
  },
  methods: {
    async loadData(sections, options) {
      options = options || {};

      let _query = null;
      if (this.T.notNothing(sections)) {
        _query = { sections: sections.join(',') };
      }
      let apiRes = await this.T.callAPI_get('/api/v1/func/overview', {
        query: _query,
        alert: { muteError: options.mute },
      });
      if (!apiRes || !apiRes.ok) return;

      this.browserServerTimeDiff = new Date(apiRes.reqTime) - new Date(apiRes.clientTime);

      for (let section in apiRes.data) {
        this[section] = apiRes.data[section];

        switch (section) {
          case 'serviceInfo':
            // 计算进度条
            let monitorInterval = this.$store.getters.SYSTEM_INFO('_MONITOR_REPORT_INTERVAL');
            this.serviceInfo.forEach(s => {
              if (s.ttl >= monitorInterval) {
                s.activePercent = 100;
                s.activeStatus  = 'success';
              } else {
                s.activePercent = s.ttl * 100 / monitorInterval;
                s.activeStatus  = 'warning';
              }
            });
            break;

          case 'latestOperations':
            // 提取对应语言
            this.latestOperations.forEach(op => {
              op.reqRouteName = op.reqRouteNames[this.$store.getters.uiLocale] || op.reqRouteNames.default;
            });
            break;
        }
      }

      this.$store.commit('updateLoadStatus', true);
    },
    showDetail(d) {
      this.$store.commit('updateHighlightedTableDataId', d.id);

      let lines = [];

      lines.push(`===== ${this.$t('Request')} =====`)

      lines.push(`${d.reqMethod.toUpperCase()} ${this.T.formatURL(d.reqRoute, {params: d.reqParamsJSON, query: d.reqQueryJSON})}`)

      if (d.reqBodyJSON) {
        lines.push(JSON.stringify(d.reqBodyJSON, null, 2));
      }
      if (d.reqFileInfoJSON) {
        lines.push(`\n===== ${this.$t('Upload')} =====`)
        d.reqFileInfoJSON.forEach(fileInfo => {
          lines.push(`${fileInfo.name} <${this.T.byteSizeHuman(fileInfo.size)}>`);
        })
      }

      lines.push(`\n===== ${this.$t('Response')} =====`)

      lines.push(`Status Code: ${d.respStatusCode}`);

      if (d.respBodyJSON) {
        lines.push(JSON.stringify(d.respBodyJSON, null, 2));
      }

      let docTEXT = lines.join('\n');

      let createTimeStr = this.M(d.createTime).format('YYYYMMDD_HHmmss');
      let fileName = `http-dump.${createTimeStr}`;
      this.$refs.longTextDialog.update(docTEXT, fileName);
    },
    serviceActiveFormat(percentage) {
      return percentage >= 100 ? this.$t('Online') : this.$t('Going Offline');
    },
    serviceActiveColor(percentage) {
      return percentage >= 100 ? 'rgb(0,128,0)' : 'orange';
    },
    overviewCountFontSize(count, k) {
      let numberLength = ('' + count).length;
      let fontSize = parseInt(80 - numberLength * 10 * (k || 1));
      return Math.max(50, fontSize);
    },
    workerQueueLoadPercentage(taskCount, processCount) {
      let taskQuota = processCount * 100;

      if (taskQuota <= 0 && taskCount > 0) return 100;
      if (taskCount === 0) return 0;

      let percentage = 100 * taskCount / taskQuota;
      if (percentage < 0) {
        percentage = 0;
      } else if (percentage > 100) {
        percentage = 100;
      }

      return percentage;
    },
    workerQueueLoadFormat(percentage) {
      return `${this.$t('Jam')}${this.$t(':')}${parseInt(percentage)}%`;
    },
  },
  computed: {
    WORKER_QUEUE_TASK_COUNT_COLORS() {
      return [
        { color: '#00aa00', percentage: 50 },
        { color: '#ff6600', percentage: 80 },
        { color: '#ff0000', percentage: 100 }
      ];
    },
    serviceInfo_servers() {
      return this.serviceInfo.filter(s => s.name === 'server');
    },
    serviceInfo_workers() {
      return this.serviceInfo.filter(s => s.name === 'worker');
    },
    serviceInfo_beat() {
      return this.serviceInfo.filter(s => s.name === 'beat');
    },
    serviceUptime_avg() {
      return {
        server: parseInt(this.serviceInfo_servers.reduce((acc, x) => acc + x.uptime, 0) / this.serviceInfo_servers.length * 1000),
        worker: parseInt(this.serviceInfo_workers.reduce((acc, x) => acc + x.uptime, 0) / this.serviceInfo_workers.length * 1000),
        beat  : parseInt(this.serviceInfo_beat.reduce((acc, x)    => acc + x.uptime, 0) / this.serviceInfo_beat.length    * 1000),
      }
    },
    serviceUptime_max() {
      return {
        server: Math.max.apply(null, this.serviceInfo_servers.map(x => x.uptime)) * 1000,
        worker: Math.max.apply(null, this.serviceInfo_workers.map(x => x.uptime)) * 1000,
        beat  : Math.max.apply(null, this.serviceInfo_beat.map(x => x.uptime))    * 1000,
      }
    },
    serviceUptime_min() {
      return {
        server: Math.min.apply(null, this.serviceInfo_servers.map(x => x.uptime)) * 1000,
        worker: Math.min.apply(null, this.serviceInfo_workers.map(x => x.uptime)) * 1000,
        beat  : Math.min.apply(null, this.serviceInfo_beat.map(x => x.uptime))    * 1000,
      }
    },
  },
  props: {
  },
  data() {
    return {
      browserServerTimeDiff: 0,
      serviceGroupCollapsed: true,

      workerQueueInfo : [],
      serviceInfo     : [],
      bizEntityInfo   : [],
      latestOperations: [],

      autoRefreshTimer: null,
    }
  },
  mounted() {
    this.autoRefreshTimer = setInterval(() => {
      this.loadData([ 'serviceInfo', 'workerQueueInfo' ], { mute: true });
      console.log(this.serviceInfo_servers)

    }, 5 * 1000);
  },
  beforeDestroy() {
    if (this.autoRefreshTimer) clearInterval(this.autoRefreshTimer);
  },
}
</script>

<style scoped>
.browser-server-time-diff {
  display: block;
  position: relative;
  padding: 0 0 10px 10px;
  font-size: 12px;
  color: red;
  z-index: 1;
}

.worker-queue-card {
  width: 300px;
  height: 150px;
  display: inline-block;
  margin: 10px 10px;
  position: relative;
}
.worker-queue-highlight {
  color: #FF6600;
  border-color: #FF6600;
}
.worker-queue-info {
  font-size: 12px;
  text-align: left;
}
.worker-queue-info .worker-queue-number {
  font-size: 40px;
  letter-spacing: 5px;
}

.service-card {
  width: 300px;
  height: 160px;
  display: inline-block;
  margin: 10px 10px;
  position: relative;
}
.service-info {
  font-size: 12px;
  text-align: left;
}
.service-info .service-name {
  text-transform: capitalize;
  font-size: 30px;
}
.service-active {
  position: absolute;
  top: 15px;
  right: 15px;
}

.service-info tr > td,
.worker-queue-info tr > td {
  vertical-align: top;
}
.service-info tr > td:first-child,
.worker-queue-info tr > td:first-child {
  white-space: nowrap;
}

.service-group-expand-button {
  margin-left: 10px;
}
.service-group-collapsed {
  display: inline-block;
}
.service-group-rest {
  display: none;
}
.service-group-count {
  width: 100px;
  height: 160px;
  display: inline-block;
  margin: 10px 30px 10px -10px;
  position: relative;
  border: none !important;
  box-shadow: none !important;
}
.service-group-count-text {
  font-size: 32px;
  position: absolute;
  bottom: 10px;
  left: 10px;
}

.biz-entity-card {
  width: 330px;
  height: 200px;
  display: inline-block;
  margin: 10px 10px;
  position: relative;
}
.biz-entity-icon {
  position: absolute;
  font-size: 200px;
  left: 130px;
  top: 40px;
  color: #f5f5f5;
  line-height: 200px;
  z-index: 0;
}
.biz-entity-icon-text {
  font-size: 120px;
}
.biz-entity-name {
  font-size: 32px;
  display: block;
  z-index: 1;
  position: relative;
}
.biz-entity-count {
  line-height: 1.5;
  font-family: sans-serif;
  display: block;
  padding-left: 20px;
  z-index: 1;
  position: relative;
  font-size: 60px;
}
.biz-entity-count-sub {
  font-size: 20px;
  position: absolute;
  right: 20px;
}
.biz-entity-count-unit {
  font-size: 40px;
  font-weight: 200;
}
</style>

<style>
.service-active .el-progress-bar {
  width: 100px;
}
.service-active .el-progress__text {
  font-size: 12px !important;
}

.worker-queue-card .el-card__body,
.service-card .el-card__body,
.service-group-count .el-card__body {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
