apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "func.fullname" . }}-worker-5
  name: {{ include "func.fullname" . }}-worker-5
spec:
  replicas: {{ .Values.worker_5.replicas }}
  selector:
    matchLabels:
      app: {{ include "func.fullname" . }}-worker-5
  template:
    metadata:
      labels:
        app: {{ include "func.fullname" . }}-worker-5
    spec:
      containers:
      - args:
        - ./run-worker-by-queue.sh
        - "5"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "func.fullname" . }}-worker-5
        resources: {{ toYaml .Values.worker_5.resources | nindent 10 }}
        volumeMounts:
        #- mountPath: /data/user-config.yaml
        #  name: user-config
        #  subPath: user-config.yaml
        - mountPath: /data
          name: data
        {{- if (eq .Values.timeZone "UTC") }}
        - mountPath: /usr/share/zoneinfo/Asia/Shanghai
          name: timezone
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      {{- if .Values.storage.pvc.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "func.fullname" . }}-resources
        {{- else }}
        - name: data
          hostPath:
            path: {{ .Values.storage.hostPath.path }}/resources
      {{- end }}
        {{- if (eq .Values.timeZone "UTC") }}
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/UTC
        {{- end}}
      {{- with .Values.storage.hostPath.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "func.fullname" . }}-worker-5
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    app: {{ include "func.fullname" . }}-worker-5
  type: ClusterIP
