apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "func.fullname" . }}-worker-8-9
  name: {{ include "func.fullname" . }}-worker-8-9
spec:
  replicas: {{ .Values.worker_8_9.replicas }}
  selector:
    matchLabels:
      app: {{ include "func.fullname" . }}-worker-8-9
  template:
    metadata:
      labels:
        app: {{ include "func.fullname" . }}-worker-8-9
    spec:
{{/*      initContainers:*/}}
{{/*      - name: init-service*/}}
{{/*        image: curlimages/curl:latest #busybox:1.28.3*/}}
{{/*        command: ['sh', '-c', 'until curl -I server:8088; do echo waiting for init-service && sleep 2; done']*/}}
      containers:
      - args:
        - ./run-worker-by-queue.sh
        - "8"
        - "9"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "func.fullname" . }}-worker-8-9
        resources: {}
        volumeMounts:
        #- mountPath: /data/user-config.yaml
        #  name: user-config
        #  subPath: user-config.yaml
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      {{- if .Values.storage.pvc.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "func.fullname" . }}-resources
        {{- else }}
        - name: data
          hostPath:
            path: {{ .Values.storage.hostPath.path }}/resources
      {{- end }}
      {{- with .Values.storage.hostPath.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "func.fullname" . }}-worker-8-9
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    app: {{ include "func.fullname" . }}-worker-8-9
  type: ClusterIP
